# Generated by Django 5.2.12 on 2026-03-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pago'),
        ('facturacion', '0004_factura_estado_pago_pagofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_factura', to='facturacion.factura'),
        ),
    ]
