# Generated by Django 5.2.12 on 2026-04-10 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan comercial',
                'verbose_name_plural': 'Planes comerciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('puede_facturas', models.BooleanField(default=False)),
                ('puede_clientes', models.BooleanField(default=False)),
                ('puede_productos', models.BooleanField(default=False)),
                ('puede_proveedores', models.BooleanField(default=False)),
                ('puede_inventario', models.BooleanField(default=False)),
                ('puede_compras', models.BooleanField(default=False)),
                ('puede_cai', models.BooleanField(default=False)),
                ('puede_impuestos', models.BooleanField(default=False)),
                ('puede_notas_credito', models.BooleanField(default=False)),
                ('puede_recibos', models.BooleanField(default=False)),
                ('puede_egresos', models.BooleanField(default=False)),
                ('puede_reportes', models.BooleanField(default=False)),
                ('puede_cxc', models.BooleanField(default=False)),
                ('puede_cxp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol del sistema',
                'verbose_name_plural': 'Roles del sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='plan_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='core.plancomercial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.rolsistema'),
        ),
        migrations.CreateModel(
            name='PlanModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plancomercial')),
            ],
            options={
                'verbose_name': 'Modulo por plan',
                'verbose_name_plural': 'Modulos por plan',
                'unique_together': {('plan', 'modulo')},
            },
        ),
    ]
