# Generated by Django 5.2.12 on 2026-04-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rolsistema_puede_ajustar_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='es_comercial',
            field=models.BooleanField(default=True),
        ),
    ]
