# Generated by Django 5.2.12 on 2026-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modulo_es_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado_licencia',
            field=models.CharField(choices=[('prueba', 'Prueba'), ('activa', 'Activa'), ('suspendida', 'Suspendida'), ('vencida', 'Vencida')], default='prueba', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_vencimiento_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observaciones_comerciales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
