# Generated by Django 5.2.12 on 2026-04-10 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_estado_licencia_empresa_fecha_inicio_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoLicenciaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('cantidad_meses', models.PositiveIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Deposito'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_licencia', to='core.empresa')),
                ('plan_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_licencia', to='core.plancomercial')),
            ],
            options={
                'verbose_name': 'Pago de licencia',
                'verbose_name_plural': 'Pagos de licencia',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
