# Generated by Django 5.2.12 on 2026-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pagolicenciaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_catalogo_cuentas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_contabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_contabilizar_asientos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_asientos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_reportes_contables',
            field=models.BooleanField(default=False),
        ),
    ]
