# Generated by Django 5.2.12 on 2026-04-13 02:29

from django.db import migrations, models


def crear_modulo_rrhh(apps, schema_editor):
    Modulo = apps.get_model("core", "Modulo")
    Modulo.objects.get_or_create(
        codigo="rrhh",
        defaults={"nombre": "Recursos Humanos", "es_comercial": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_modulo_contabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_configuracion_rrhh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_empleados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_planillas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_rrhh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_vacaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(crear_modulo_rrhh, migrations.RunPython.noop),
    ]
