# Generated by Django 5.2.12 on 2026-04-19 02:22

import django.db.models.deletion
from django.db import migrations, models


def activar_paquete_hospital_mia(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    ConfiguracionAvanzadaEmpresa = apps.get_model('core', 'ConfiguracionAvanzadaEmpresa')
    empresa = Empresa.objects.filter(slug='hospital_mia').first()
    if not empresa:
        return
    ConfiguracionAvanzadaEmpresa.objects.update_or_create(
        empresa=empresa,
        defaults={
            'usa_cierre_caja': True,
            'usa_pagos_mixtos': True,
            'usa_reporte_bancos': True,
            'usa_inventario_farmaceutico': True,
            'usa_bodegas_internas': True,
            'ventas_solo_desde_vitrina': True,
            'bodega_venta_predeterminada': 'Vitrina',
            'notas': 'Paquete Farmacia/Drogueria activado por implementacion Hospital MIA.',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_modulo_agenda_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAvanzadaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_cierre_caja', models.BooleanField(default=False)),
                ('usa_pagos_mixtos', models.BooleanField(default=False)),
                ('usa_reporte_bancos', models.BooleanField(default=False)),
                ('usa_inventario_farmaceutico', models.BooleanField(default=False)),
                ('usa_bodegas_internas', models.BooleanField(default=False)),
                ('ventas_solo_desde_vitrina', models.BooleanField(default=False)),
                ('bodega_venta_predeterminada', models.CharField(default='Vitrina', max_length=80)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_avanzada', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion avanzada por empresa',
                'verbose_name_plural': 'Configuraciones avanzadas por empresa',
            },
        ),
        migrations.RunPython(activar_paquete_hospital_mia, migrations.RunPython.noop),
    ]
