# Generated by Django 5.2.12 on 2026-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracionpowerbiempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionavanzadaempresa',
            name='permite_plantilla_factura_independiente',
            field=models.BooleanField(default=False),
        ),
    ]
