# Generated by Django 5.2.12 on 2026-06-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_modulo_punto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_configuracion_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_expediente_clinico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_tratamientos_clinicos',
            field=models.BooleanField(default=False),
        ),
    ]
