# Generated by Django 5.2.12 on 2026-06-06 05:51

from django.db import migrations


def crear_modulo_clinica(apps, schema_editor):
    Modulo = apps.get_model("core", "Modulo")
    Modulo.objects.update_or_create(
        codigo="clinica_medica",
        defaults={
            "nombre": "Clinica Medica",
            "es_comercial": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rolsistema_puede_clinica_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_modulo_clinica, migrations.RunPython.noop),
    ]
