# Generated by Django 5.2.12 on 2026-06-18 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_activar_pos_empresas_medicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creacion'), ('modificar', 'Modificacion'), ('eliminar', 'Eliminacion'), ('relacion', 'Cambio de relacion')], max_length=20)),
                ('modulo', models.CharField(db_index=True, max_length=40)),
                ('app_label', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(db_index=True, max_length=100)),
                ('objeto_representacion', models.CharField(max_length=300)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, max_length=500)),
                ('ruta', models.CharField(blank=True, max_length=500)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente_usuario', models.CharField(blank=True, max_length=500)),
                ('identificador_solicitud', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_auditoria', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empresa', '-fecha'], name='core_regist_empresa_cea847_idx'), models.Index(fields=['empresa', 'app_label', 'modelo', 'objeto_id'], name='core_regist_empresa_e32180_idx'), models.Index(fields=['usuario', '-fecha'], name='core_regist_usuario_28ad98_idx')],
            },
        ),
    ]
