# Generated by Django 5.2.12 on 2026-06-18 23:21

from django.db import migrations, models


def conservar_acceso_pos_existente(apps, schema_editor):
    RolSistema = apps.get_model('core', 'RolSistema')
    RolSistema.objects.filter(
        puede_facturas=True,
        puede_productos=True,
    ).update(puede_punto_venta=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_punto_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(conservar_acceso_pos_existente, migrations.RunPython.noop),
    ]
