# Generated by Django 5.2.12 on 2026-06-19 00:14

from django.db import migrations, models


def conservar_accesos_operativos(apps, schema_editor):
    RolSistema = apps.get_model('core', 'RolSistema')
    RolSistema.objects.filter(puede_facturas=True).update(
        puede_configuracion_facturacion=True,
    )
    RolSistema.objects.filter(
        models.Q(puede_punto_venta=True) | models.Q(puede_recibos=True)
    ).update(puede_cierres_caja=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rol_punto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_cierres_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_configuracion_facturacion',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(conservar_accesos_operativos, migrations.RunPython.noop),
    ]
