# Generated by Django 5.2.12 on 2026-07-25 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_permiso_ver_facturas(apps, schema_editor):
    RolSistema = apps.get_model('core', 'RolSistema')
    RolSistema.objects.filter(puede_facturas=True).update(puede_ver_facturas=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_modulo_cotizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_facturas',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UsuarioEmpresaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuarios', to='core.empresa')),
                ('rol_sistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos_empresa_usuario', to='core.rolsistema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_por_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de usuario por empresa',
                'verbose_name_plural': 'Permisos de usuarios por empresa',
                'ordering': ['empresa__nombre'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
        migrations.RunPython(copiar_permiso_ver_facturas, migrations.RunPython.noop),
    ]
