# Generated by Django 5.2.12 on 2026-08-16 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_usuario_retiro_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionOnix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('modelo', models.CharField(default='gpt-5.6-luna', max_length=80)),
                ('instrucciones_empresa', models.TextField(blank=True, help_text='Preferencias operativas aprobadas que Onix debe aplicar solo a esta empresa.')),
                ('herramientas_consulta_activas', models.BooleanField(default=True)),
                ('limite_tokens_mensual', models.PositiveBigIntegerField(default=500000, help_text='Cero significa sin limite interno de tokens.')),
                ('voz_activa', models.BooleanField(default=False, help_text='Reservado para la segunda fase de Onix por voz.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_onix', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion de Onix',
                'verbose_name_plural': 'Configuraciones de Onix',
            },
        ),
        migrations.CreateModel(
            name='ConversacionOnix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Conversacion con Onix', max_length=160)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_onix', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_onix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversacion de Onix',
                'verbose_name_plural': 'Conversaciones de Onix',
                'ordering': ['-fecha_actualizacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoOnix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('respuesta_id', models.CharField(blank=True, max_length=120)),
                ('tokens_entrada', models.PositiveBigIntegerField(default=0)),
                ('tokens_entrada_cache', models.PositiveBigIntegerField(default=0)),
                ('tokens_salida', models.PositiveBigIntegerField(default=0)),
                ('tokens_total', models.PositiveBigIntegerField(default=0)),
                ('costo_estimado_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('llamadas_herramientas', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_onix', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_onix', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='core.conversaciononix')),
            ],
            options={
                'verbose_name': 'Consumo de Onix',
                'verbose_name_plural': 'Consumos de Onix',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeOnix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Onix')], max_length=12)),
                ('contenido', models.TextField()),
                ('pagina', models.CharField(blank=True, max_length=500)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversaciononix')),
            ],
            options={
                'verbose_name': 'Mensaje de Onix',
                'verbose_name_plural': 'Mensajes de Onix',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversaciononix',
            index=models.Index(fields=['empresa', 'usuario', 'activa'], name='core_conver_empresa_df16e2_idx'),
        ),
        migrations.AddIndex(
            model_name='consumoonix',
            index=models.Index(fields=['empresa', 'fecha'], name='core_consum_empresa_177d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeonix',
            index=models.Index(fields=['conversacion', 'fecha'], name='core_mensaj_convers_128641_idx'),
        ),
    ]
