# Generated by Django 5.2.12 on 2026-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_habilitar_rrhh_clinicas_solicitadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='puede_cambiar_fecha_factura',
            field=models.BooleanField(default=False),
        ),
    ]
