# Generated by Django 5.2.12 on 2026-09-23 20:38

import django.db.models.deletion
from django.db import migrations, models


def crear_roles_clinicos_iniciales(apps, schema_editor):
    RolSistema = apps.get_model("core", "RolSistema")
    permisos_en_modelo = {
        field.name: False for field in RolSistema._meta.fields if field.name.startswith("puede_")
    }
    base = {
        **permisos_en_modelo,
        "es_rol_clinico": True,
        "usa_permisos_clinicos_granulares": True,
        "activo": True,
    }
    roles = {
        "clinico-recepcion": {
            "nombre": "RECEPCIÓN",
            "descripcion": "Agenda, datos generales, recordatorios, facturación nueva, manuales y carga de anexos.",
            "puede_ver_calendario": True,
            "puede_crear_citas": True,
            "puede_ver_pacientes": True,
            "puede_ver_datos_generales_paciente": True,
            "puede_crear_recordatorios_paciente": True,
            "puede_crear_facturas": True,
            "puede_ver_manuales_pdf": True,
            "puede_enviar_manuales_pdf": True,
            "puede_subir_anexos_clinicos": True,
        },
        "clinico-recepcion-medical-spa": {
            "nombre": "RECEPCIÓN · MEDICAL SPA",
            "descripcion": "Recepción con consulta adicional de facturas anteriores para medical_spa.",
            "puede_ver_calendario": True,
            "puede_crear_citas": True,
            "puede_ver_pacientes": True,
            "puede_ver_datos_generales_paciente": True,
            "puede_crear_recordatorios_paciente": True,
            "puede_crear_facturas": True,
            "puede_ver_facturas": True,
            "puede_ver_manuales_pdf": True,
            "puede_enviar_manuales_pdf": True,
            "puede_subir_anexos_clinicos": True,
        },
        "clinico-enfermera": {
            "nombre": "ENFERMERA",
            "descripcion": "Calendario, plan y tratamiento, Enfermería, Terapias y carga de anexos.",
            "puede_ver_calendario": True,
            "puede_ver_pacientes": True,
            "puede_ver_datos_generales_paciente": True,
            "puede_ver_planes_tratamiento": True,
            "puede_escribir_enfermeria": True,
            "puede_ver_terapias": True,
            "puede_escribir_terapias": True,
            "puede_subir_anexos_clinicos": True,
        },
        "clinico-encargado-bodega": {
            "nombre": "ENCARGADO DE BODEGA",
            "descripcion": "Inventario, productos, transferencias rápidas, facturas nuevas y proveedores.",
            "puede_inventario": True,
            "puede_productos": True,
            "puede_crear_productos": True,
            "puede_transferir_inventario": True,
            "puede_crear_facturas": True,
            "puede_proveedores": True,
            "puede_crear_proveedores": True,
            "puede_editar_proveedores": True,
        },
    }
    for codigo, valores in roles.items():
        RolSistema.objects.update_or_create(codigo=codigo, defaults={**base, **valores})


def conservar_roles_clinicos(apps, schema_editor):
    # No se eliminan en reversa porque podrían haber sido editados o asignados.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_permiso_cambiar_fecha_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolsistema',
            name='es_rol_clinico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_administrar_manuales_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_citas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_historia_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_recetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_crear_recordatorios_paciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_editar_citas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_editar_historia_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_editar_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_editar_planes_tratamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_eliminar_anexos_clinicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_eliminar_citas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_eliminar_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_enviar_manuales_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_enviar_recetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_escribir_camara_hiperbarica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_escribir_enfermeria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_escribir_postquirurgicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_escribir_terapias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_subir_anexos_clinicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_transferir_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_anexos_clinicos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_calendario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_camara_hiperbarica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_datos_generales_paciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_historia_clinica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_manuales_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_pacientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_planes_tratamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_postquirurgicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_recetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='puede_ver_terapias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolsistema',
            name='usa_permisos_clinicos_granulares',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioempresapermiso',
            name='rol_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_empresa_usuario', to='core.rolsistema'),
        ),
        migrations.RunPython(crear_roles_clinicos_iniciales, conservar_roles_clinicos),
    ]
