from django.urls import path
from .views import (
    cerrar_sesion,
    dashboard,
    empresa_login,
    superadmin_dashboard,
    superadmin_empresas,
    superadmin_empresa_create,
    superadmin_empresa_detail,
    superadmin_empresa_edit,
    superadmin_empresa_activar_licencia,
    superadmin_empresa_registrar_pago_licencia,
    superadmin_empresa_suspender_licencia,
    superadmin_login,
    superadmin_licencias,
    superadmin_modulos,
    superadmin_logout,
    superadmin_plan_create,
    superadmin_plan_edit,
    superadmin_planes,
    superadmin_rol_create,
    superadmin_rol_edit,
    superadmin_roles,
    superadmin_usuario_create,
    superadmin_usuario_edit,
    superadmin_usuarios,
    asistente_consulta,
)

urlpatterns = [
    path('control/login/', superadmin_login, name='superadmin_login'),
    path('control/logout/', superadmin_logout, name='superadmin_logout'),
    path('control/', superadmin_dashboard, name='superadmin_dashboard'),
    path('control/empresas/', superadmin_empresas, name='superadmin_empresas'),
    path('control/empresas/nueva/', superadmin_empresa_create, name='superadmin_empresa_create'),
    path('control/empresas/<int:empresa_id>/', superadmin_empresa_detail, name='superadmin_empresa_detail'),
    path('control/empresas/<int:empresa_id>/editar/', superadmin_empresa_edit, name='superadmin_empresa_edit'),
    path('control/empresas/<int:empresa_id>/licencia/activar/', superadmin_empresa_activar_licencia, name='superadmin_empresa_activar_licencia'),
    path('control/empresas/<int:empresa_id>/licencia/pago/', superadmin_empresa_registrar_pago_licencia, name='superadmin_empresa_registrar_pago_licencia'),
    path('control/empresas/<int:empresa_id>/licencia/suspender/', superadmin_empresa_suspender_licencia, name='superadmin_empresa_suspender_licencia'),
    path('control/usuarios/', superadmin_usuarios, name='superadmin_usuarios'),
    path('control/usuarios/nuevo/', superadmin_usuario_create, name='superadmin_usuario_create'),
    path('control/usuarios/<int:usuario_id>/editar/', superadmin_usuario_edit, name='superadmin_usuario_edit'),
    path('control/planes/', superadmin_planes, name='superadmin_planes'),
    path('control/planes/nuevo/', superadmin_plan_create, name='superadmin_plan_create'),
    path('control/planes/<int:plan_id>/editar/', superadmin_plan_edit, name='superadmin_plan_edit'),
    path('control/roles/', superadmin_roles, name='superadmin_roles'),
    path('control/roles/nuevo/', superadmin_rol_create, name='superadmin_rol_create'),
    path('control/roles/<int:rol_id>/editar/', superadmin_rol_edit, name='superadmin_rol_edit'),
    path('control/modulos/', superadmin_modulos, name='superadmin_modulos'),
    path('control/licencias/', superadmin_licencias, name='superadmin_licencias'),
    path('', empresa_login, name='empresa_login_host'),
    path('dashboard/asistente/consulta/', asistente_consulta, name='asistente_consulta_host'),
    path('dashboard/', dashboard, name='dashboard_host'),
    path('logout/', cerrar_sesion, name='cerrar_sesion_host'),
    path('<slug:slug>/', empresa_login, name='empresa_login'),
    path('<slug:slug>/dashboard/asistente/consulta/', asistente_consulta, name='asistente_consulta'),
    path('<slug:slug>/dashboard/', dashboard, name='dashboard'),
    path('<slug:slug>/logout/', cerrar_sesion, name='cerrar_sesion'),
]
