# Generated by Django 6.0.2 on 2026-03-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('HNL', 'Lempiras'), ('USD', 'Dólares')], default='HNL', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_lempiras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.cai'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
