# Generated by Django 5.2.12 on 2026-03-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_estado_pago_pagofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_facturacion', to='facturacion.factura'),
        ),
    ]
