# Generated by Django 5.2.12 on 2026-03-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_pagofactura_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofactura',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
