# Generated by Django 5.2.12 on 2026-03-19 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_pagofactura_metodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_vendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
