# Generated by Django 5.2.12 on 2026-03-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_factura_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
