# Generated by Django 5.2.12 on 2026-03-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_lineafactura_descuento_monto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='constancia_exonerado',
            new_name='registro_exonerado',
        ),
    ]
