# Generated by Django 5.2.12 on 2026-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_rename_constancia_exonerado_factura_registro_exonerado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineafactura',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
