# Generated by Django 5.2.12 on 2026-04-08 03:08

from django.db import migrations, models


def copiar_snapshot_cai(apps, schema_editor):
    Factura = apps.get_model('facturacion', 'Factura')

    for factura in Factura.objects.select_related('cai').exclude(cai__isnull=True):
        cai = factura.cai
        factura.cai_numero = cai.numero_cai
        factura.cai_establecimiento = cai.establecimiento
        factura.cai_punto_emision = cai.punto_emision
        factura.cai_tipo_documento = cai.tipo_documento
        factura.cai_rango_inicial = cai.rango_inicial
        factura.cai_rango_final = cai.rango_final
        factura.cai_fecha_limite = cai.fecha_limite
        factura.save(update_fields=[
            'cai_numero',
            'cai_establecimiento',
            'cai_punto_emision',
            'cai_tipo_documento',
            'cai_rango_inicial',
            'cai_rango_final',
            'cai_fecha_limite',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_lineafactura_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cai_establecimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_punto_emision',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_rango_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_rango_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cai_tipo_documento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RunPython(copiar_snapshot_cai, migrations.RunPython.noop),
    ]
