# Generated by Django 5.2.12 on 2026-04-08 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
        ('facturacion', '0012_factura_cai_establecimiento_factura_cai_fecha_limite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('HNL', 'Lempiras'), ('USD', 'Dólares')], default='HNL', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('numero_nota', models.CharField(blank=True, max_length=20, null=True)),
                ('cai_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('cai_establecimiento', models.CharField(blank=True, max_length=3, null=True)),
                ('cai_punto_emision', models.CharField(blank=True, max_length=3, null=True)),
                ('cai_tipo_documento', models.CharField(blank=True, max_length=2, null=True)),
                ('cai_rango_inicial', models.IntegerField(blank=True, null=True)),
                ('cai_rango_final', models.IntegerField(blank=True, null=True)),
                ('cai_fecha_limite', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_lempiras', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.cai')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('factura_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion.factura')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoimpuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.notacredito')),
            ],
        ),
    ]
