# Generated by Django 5.2.12 on 2026-04-08 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
        ('facturacion', '0013_notacredito_lineanotacredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pago', to='facturacion.factura')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='facturacion.pagofactura')),
            ],
        ),
    ]
