# Generated by Django 5.2.12 on 2026-04-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_recibopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='controla_inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_predeterminados', to='facturacion.tipoimpuesto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_item',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('libra', 'Libra'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('galon', 'Galon'), ('hora', 'Hora'), ('dia', 'Dia'), ('mes', 'Mes'), ('servicio', 'Servicio')], default='unidad', max_length=20),
        ),
    ]
