# Generated by Django 5.2.12 on 2026-04-08 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
        ('facturacion', '0015_producto_codigo_producto_controla_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='facturacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida_factura', 'Salida por Factura'), ('devolucion_nota_credito', 'Entrada por Nota de Credito'), ('ajuste_entrada', 'Ajuste Positivo'), ('ajuste_salida', 'Ajuste Negativo'), ('reversion_factura', 'Reversion de Factura'), ('reversion_nota_credito', 'Reversion de Nota de Credito')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existencia_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('existencia_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura')),
                ('nota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.notacredito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='facturacion.producto')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
