# Generated by Django 5.2.12 on 2026-04-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_inventarioproducto_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cai',
            name='uso_documento',
            field=models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de Credito')], default='factura', max_length=20),
        ),
    ]
