# Generated by Django 5.2.12 on 2026-04-08 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
        ('facturacion', '0017_cai_uso_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=120)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aplicada', 'Aplicada')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_documento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='entrada_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.entradainventariodocumento'),
        ),
        migrations.CreateModel(
            name='LineaEntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comentario', models.CharField(blank=True, max_length=150, null=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.entradainventariodocumento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto')),
            ],
        ),
    ]
