# Generated by Django 5.2.12 on 2026-04-09 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pago_factura'),
        ('facturacion', '0022_pagocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteEgresoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_egreso', to='facturacion.comprainventario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='facturacion.pagocompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.proveedor')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
