# Generated by Django 5.2.12 on 2026-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_comprobanteegresocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainventario',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=20),
        ),
        migrations.AddField(
            model_name='comprainventario',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprainventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
