# Generated by Django 5.2.12 on 2026-04-11 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_modulo_contabilidad'),
        ('facturacion', '0024_comprainventario_condicion_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompraFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('proveedor_rtn', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_factura', models.CharField(max_length=120)),
                ('cai', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_documento', models.DateField()),
                ('periodo_anio', models.PositiveIntegerField()),
                ('periodo_mes', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_15', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isv_15', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_18', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isv_18', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exonerado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('anulada', 'Anulada')], default='registrada', max_length=15)),
                ('origen_importacion', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proveedor')),
            ],
            options={
                'ordering': ['-fecha_documento', '-id'],
                'indexes': [models.Index(fields=['empresa', 'numero_factura'], name='facturacion_empresa_13f755_idx'), models.Index(fields=['empresa', 'periodo_anio', 'periodo_mes'], name='facturacion_empresa_9797de_idx')],
            },
        ),
    ]
