# Generated by Django 5.2.12 on 2026-04-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_clasificacioncomprafiscal'),
        ('facturacion', '0025_registrocomprafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='clasificacion_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_fiscales', to='contabilidad.clasificacioncomprafiscal'),
        ),
    ]
