# Generated by Django 5.2.12 on 2026-04-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_movimientobancario_conciliado_and_more'),
        ('facturacion', '0026_registrocomprafiscal_clasificacion_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='cuenta_financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_facturas', to='contabilidad.cuentafinanciera'),
        ),
    ]
