# Generated by Django 5.2.12 on 2026-04-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_modulo_contabilidad'),
        ('facturacion', '0027_pagocompra_cuenta_financiera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla_factura_pdf', models.CharField(choices=[('normal', 'Factura clasica'), ('alternativa', 'Factura alternativa')], default='normal', max_length=20)),
                ('nombre_comercial_documentos', models.CharField(blank=True, max_length=200, null=True)),
                ('color_primario', models.CharField(default='#334155', max_length=20)),
                ('color_secundario', models.CharField(default='#94a3b8', max_length=20)),
                ('mostrar_vendedor', models.BooleanField(default=False)),
                ('mostrar_descuentos', models.BooleanField(default=True)),
                ('mostrar_notas_linea', models.BooleanField(default=True)),
                ('leyenda_factura', models.CharField(blank=True, max_length=255, null=True)),
                ('pie_factura', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_facturacion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion de facturacion por empresa',
                'verbose_name_plural': 'Configuraciones de facturacion por empresa',
            },
        ),
    ]
