# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0014_movimientobancario_pago_factura"),
        ("facturacion", "0028_configuracionfacturacionempresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocompra",
            name="cuenta_financiera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_compras",
                to="contabilidad.cuentafinanciera",
            ),
        ),
    ]
