# Generated by Django 5.2.12 on 2026-04-19 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracionavanzadaempresa'),
        ('facturacion', '0030_cliente_crm_fields_producto_fecha_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofactura',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_facturas_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('general', 'General'), ('manana', 'Manana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='general', max_length=20)),
                ('efectivo_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferencia_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_reportado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta_reportado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferencia_reportado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('cerrado', 'Cerrado'), ('revisado', 'Revisado'), ('anulado', 'Anulado')], default='cerrado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_caja', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
                'unique_together': {('empresa', 'cajero', 'fecha', 'turno')},
            },
        ),
    ]
