# Generated by Django 5.2.12 on 2026-04-19 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracionavanzadaempresa'),
        ('facturacion', '0031_pagofactura_cajero_cierrecaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('principal', 'Bodega principal'), ('provisional', 'Bodega provisional'), ('vitrina', 'Vitrina'), ('otra', 'Otra')], default='otra', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas_inventario', to='core.empresa')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_inventario', to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_inventario', to='facturacion.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_inventario', to='facturacion.proveedor')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'producto__nombre', 'numero_lote'],
                'unique_together': {('empresa', 'producto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoLoteBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida_factura', 'Salida por factura'), ('traslado_salida', 'Traslado salida'), ('traslado_entrada', 'Traslado entrada'), ('ajuste', 'Ajuste'), ('reversion', 'Reversion')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existencia_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('existencia_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=140, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='facturacion.bodegainventario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_lote_bodega', to='core.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_lotes', to='facturacion.factura')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bodega', to='facturacion.loteinventario')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExistenciaLoteBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='facturacion.bodegainventario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias_lote_bodega', to='core.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias_bodega', to='facturacion.loteinventario')),
            ],
            options={
                'ordering': ['bodega__nombre', 'lote__producto__nombre', 'lote__fecha_vencimiento'],
                'unique_together': {('bodega', 'lote')},
            },
        ),
    ]
