# Generated by Django 5.2.12 on 2026-04-19 20:24

import django.db.models.deletion
from django.db import migrations, models


def crear_categorias_base_hospital_mia(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    CategoriaProductoFarmaceutico = apps.get_model('facturacion', 'CategoriaProductoFarmaceutico')
    empresa = Empresa.objects.filter(slug='hospital_mia').first()
    if not empresa:
        return

    categorias = [
        ('Medicamentos', 'Medicamentos de venta general o bajo indicacion medica.', True, False, False),
        ('Insumos medicos', 'Insumos de uso clinico, curaciones y apoyo medico.', False, False, False),
        ('Material quirurgico', 'Material asociado a procedimientos quirurgicos o clinicos.', False, False, False),
        ('Estetica y capilar', 'Productos de medicina estetica, cuidado capilar o cosmetico.', False, False, False),
        ('Refrigerados', 'Productos que requieren cadena fria o almacenamiento especial.', False, True, False),
        ('Controlados', 'Productos con control especial interno o regulatorio.', True, False, True),
    ]
    for nombre, descripcion, receta, refrigeracion, controlado in categorias:
        CategoriaProductoFarmaceutico.objects.get_or_create(
            empresa=empresa,
            nombre=nombre,
            defaults={
                'descripcion': descripcion,
                'requiere_receta_default': receta,
                'requiere_refrigeracion_default': refrigeracion,
                'producto_controlado_default': controlado,
                'activa': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracionavanzadaempresa'),
        ('facturacion', '0032_bodegainventario_loteinventario_movimientolotebodega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductoFarmaceutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_receta_default', models.BooleanField(default=False)),
                ('requiere_refrigeracion_default', models.BooleanField(default=False)),
                ('producto_controlado_default', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_farmaceuticas', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PerfilFarmaceuticoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principio_activo', models.CharField(blank=True, max_length=160, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=160, null=True)),
                ('concentracion', models.CharField(blank=True, max_length=120, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=160, null=True)),
                ('registro_sanitario', models.CharField(blank=True, max_length=120, null=True)),
                ('requiere_receta', models.BooleanField(default=False)),
                ('requiere_refrigeracion', models.BooleanField(default=False)),
                ('producto_controlado', models.BooleanField(default=False)),
                ('alerta_vencimiento_dias', models.PositiveIntegerField(default=60)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='facturacion.categoriaproductofarmaceutico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_farmaceuticos_producto', to='core.empresa')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_farmaceutico', to='facturacion.producto')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.RunPython(crear_categorias_base_hospital_mia, migrations.RunPython.noop),
    ]
