# Generated by Django 5.2.12 on 2026-05-13 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0037_lineafactura_descripcion_manual_y_producto_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineanotacredito',
            name='descripcion_manual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionfacturacionempresa',
            name='plantilla_factura_pdf',
            field=models.CharField(choices=[('normal', 'Factura clasica'), ('alternativa', 'Factura alternativa'), ('notas_extensas', 'Factura notas extensas')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='lineanotacredito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto'),
        ),
    ]
