# Generated by Django 5.2.12 on 2026-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0038_lineanotacredito_descripcion_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacturacionempresa',
            name='plantilla_factura_pdf',
            field=models.CharField(choices=[('normal', 'Factura clasica'), ('alternativa', 'Factura alternativa'), ('notas_extensas', 'Factura notas extensas'), ('independiente', 'Factura independiente')], default='normal', max_length=20),
        ),
    ]
