# Generated by Django 5.2.12 on 2026-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0042_cliente_cuenta_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopago',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
