# Generated by Django 5.2.12 on 2026-06-08 04:02

from django.db import migrations


def configurar_bodegas_medicas(apps, schema_editor):
    Empresa = apps.get_model("core", "Empresa")
    ConfiguracionAvanzadaEmpresa = apps.get_model("core", "ConfiguracionAvanzadaEmpresa")
    BodegaInventario = apps.get_model("facturacion", "BodegaInventario")

    for slug in ["hospital_mia", "medical_spa"]:
        empresa = Empresa.objects.filter(slug=slug).first()
        if not empresa:
            continue

        config, _ = ConfiguracionAvanzadaEmpresa.objects.get_or_create(empresa=empresa)
        config.usa_bodegas_internas = True
        config.usa_inventario_farmaceutico = True
        config.bodega_venta_predeterminada = "Vitrina"
        config.save(update_fields=[
            "usa_bodegas_internas",
            "usa_inventario_farmaceutico",
            "bodega_venta_predeterminada",
        ])

        for nombre, tipo in [
            ("Bodega General", "principal"),
            ("Bodega Hospital", "provisional"),
            ("Vitrina", "vitrina"),
        ]:
            bodega, _ = BodegaInventario.objects.get_or_create(
                empresa=empresa,
                nombre=nombre,
                defaults={"tipo": tipo, "activa": True},
            )
            cambios = []
            if bodega.tipo != tipo:
                bodega.tipo = tipo
                cambios.append("tipo")
            if not bodega.activa:
                bodega.activa = True
                cambios.append("activa")
            if cambios:
                bodega.save(update_fields=cambios)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0045_producto_baja_bitacora'),
    ]

    operations = [
        migrations.RunPython(configurar_bodegas_medicas, migrations.RunPython.noop),
    ]
