# Generated by Django 5.2.12 on 2026-06-18 23:55

from django.db import migrations, models


def activar_precios_finales_medical_spa(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    Configuracion = apps.get_model('facturacion', 'ConfiguracionFacturacionEmpresa')
    empresa = Empresa.objects.filter(slug='medical_spa').first()
    if empresa:
        configuracion, _ = Configuracion.objects.get_or_create(empresa=empresa)
        configuracion.precios_incluyen_impuesto = True
        configuracion.save(update_fields=['precios_incluyen_impuesto'])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0049_habilitar_pos_termico_demo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacionempresa',
            name='precios_incluyen_impuesto',
            field=models.BooleanField(default=False, help_text='El precio del catalogo se interpreta como total final con impuesto incluido.'),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='precio_incluye_impuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineanotacredito',
            name='precio_incluye_impuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(activar_precios_finales_medical_spa, migrations.RunPython.noop),
    ]
