# Generated by Django 5.2.12 on 2026-06-19 00:07

from django.db import migrations, models


def activar_precios_finales_todas_empresas(apps, schema_editor):
    Configuracion = apps.get_model('facturacion', 'ConfiguracionFacturacionEmpresa')
    Configuracion.objects.update(precios_incluyen_impuesto=True)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0050_precios_impuesto_incluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacturacionempresa',
            name='precios_incluyen_impuesto',
            field=models.BooleanField(default=True, help_text='El precio del catalogo se interpreta como total final con impuesto incluido.'),
        ),
        migrations.RunPython(activar_precios_finales_todas_empresas, migrations.RunPython.noop),
    ]
