# Generated by Django 5.2.12 on 2026-06-19 15:55

from django.db import migrations, models
from django.db.models import DecimalField, ExpressionWrapper, F, Sum


def calcular_costos_promedio(apps, schema_editor):
    Producto = apps.get_model('facturacion', 'Producto')
    LineaCompra = apps.get_model('facturacion', 'LineaCompraInventario')
    totales = (
        LineaCompra.objects.filter(compra__estado='aplicada', cantidad__gt=0)
        .values('producto_id')
        .annotate(
            unidades=Sum('cantidad'),
            valor=Sum(
                ExpressionWrapper(
                    F('cantidad') * F('costo_unitario'),
                    output_field=DecimalField(max_digits=24, decimal_places=4),
                )
            ),
        )
    )
    for total in totales.iterator():
        if total['unidades']:
            promedio = total['valor'] / total['unidades']
            Producto.objects.filter(pk=total['producto_id']).update(costo_promedio=promedio)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0051_precios_finales_todas_empresas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lineanotacredito',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.RunPython(calcular_costos_promedio, migrations.RunPython.noop),
    ]
