# Generated by Django 5.2.12 on 2026-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0053_limitar_precios_finales_empresas_clinicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_real_inventario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
