# Generated by Codex on 2026-07-09

from django.db import migrations


def configurar_bodegas_luque_aestetic(apps, schema_editor):
    Empresa = apps.get_model("core", "Empresa")
    ConfiguracionAvanzadaEmpresa = apps.get_model("core", "ConfiguracionAvanzadaEmpresa")
    BodegaInventario = apps.get_model("facturacion", "BodegaInventario")
    ExistenciaLoteBodega = apps.get_model("facturacion", "ExistenciaLoteBodega")

    empresa = Empresa.objects.filter(slug="luque_aestetic").first()
    if not empresa:
        return

    config, _ = ConfiguracionAvanzadaEmpresa.objects.get_or_create(empresa=empresa)
    config.usa_bodegas_internas = True
    config.usa_inventario_farmaceutico = True
    config.ventas_solo_desde_vitrina = False
    config.bodega_venta_predeterminada = "Bodega Clinica"
    config.save(
        update_fields=[
            "usa_bodegas_internas",
            "usa_inventario_farmaceutico",
            "ventas_solo_desde_vitrina",
            "bodega_venta_predeterminada",
        ]
    )

    bodegas_objetivo = []
    for nombre, tipo in [
        ("Bodega Principal", "principal"),
        ("Bodega Clinica", "provisional"),
    ]:
        bodega = (
            BodegaInventario.objects.filter(empresa=empresa, nombre__iexact=nombre).first()
            or BodegaInventario.objects.filter(empresa=empresa, tipo=tipo).order_by("id").first()
        )
        if not bodega:
            bodega = BodegaInventario.objects.create(
                empresa=empresa,
                nombre=nombre,
                tipo=tipo,
                activa=True,
            )
        bodegas_objetivo.append(bodega.id)
        cambios = []
        if bodega.nombre != nombre and not BodegaInventario.objects.filter(
            empresa=empresa,
            nombre__iexact=nombre,
        ).exclude(id=bodega.id).exists():
            bodega.nombre = nombre
            cambios.append("nombre")
        if bodega.tipo != tipo:
            bodega.tipo = tipo
            cambios.append("tipo")
        if not bodega.activa:
            bodega.activa = True
            cambios.append("activa")
        if cambios:
            bodega.save(update_fields=cambios)

    for bodega in BodegaInventario.objects.filter(empresa=empresa, activa=True).exclude(id__in=bodegas_objetivo):
        tiene_existencia = ExistenciaLoteBodega.objects.filter(
            empresa=empresa,
            bodega=bodega,
            cantidad__gt=0,
        ).exists()
        if not tiene_existencia:
            bodega.activa = False
            bodega.save(update_fields=["activa"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_rol_eliminar_facturas_emitidas"),
        ("facturacion", "0057_movimientoinventario_bodega"),
    ]

    operations = [
        migrations.RunPython(configurar_bodegas_luque_aestetic, migrations.RunPython.noop),
    ]
