# Generated by Django 5.2.12 on 2026-07-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rol_eliminar_facturas_emitidas'),
        ('facturacion', '0059_cero_facturas_anuladas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionPuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Promocion 3 + 1 gratis', max_length=120)),
                ('activa', models.BooleanField(default=False)),
                ('cantidad_pagada', models.PositiveIntegerField(default=3)),
                ('cantidad_gratis', models.PositiveIntegerField(default=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_pos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Promocion de punto de venta',
                'verbose_name_plural': 'Promociones de punto de venta',
                'ordering': ['empresa__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPromocionPuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_pos', to='facturacion.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_configurados', to='facturacion.promocionpuntoventa')),
            ],
            options={
                'verbose_name': 'Producto en promocion POS',
                'verbose_name_plural': 'Productos en promocion POS',
                'ordering': ['producto__nombre'],
                'unique_together': {('promocion', 'producto')},
            },
        ),
    ]
