# Generated by Django 5.2.12 on 2026-07-16 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rol_eliminar_facturas_emitidas'),
        ('facturacion', '0062_plantilla_ejecutiva_amkt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('HNL', 'Lempiras'), ('USD', 'Dólares')], default='HNL', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('asunto', models.CharField(blank=True, max_length=180, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_lempiras', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida a factura')], default='borrador', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.empresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', '-fecha_creacion'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_generadas', to='facturacion.cotizacion'),
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_incluye_impuesto', models.BooleanField(default=False)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='facturacion.cotizacion')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoimpuesto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.producto')),
            ],
        ),
    ]
