# Generated by Django 5.2.12 on 2026-07-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0064_precio_final_serviciosmedicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainventario',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='comprobanteegresocompra',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='efectivo', max_length=20),
        ),
    ]
