# Generated by Django 5.2.12 on 2026-07-31 16:07

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal


def backfill_totales_lineas_compra(apps, schema_editor):
    LineaCompraInventario = apps.get_model('facturacion', 'LineaCompraInventario')
    for linea in LineaCompraInventario.objects.all().iterator():
        cantidad = Decimal(linea.cantidad or 0)
        costo = Decimal(linea.costo_unitario or 0)
        linea.subtotal = (cantidad * costo).quantize(Decimal("0.01"))
        linea.descuento_porcentaje = Decimal("0.00")
        linea.descuento_monto = Decimal("0.00")
        linea.impuesto_monto = Decimal("0.00")
        linea.save(update_fields=[
            "subtotal",
            "descuento_porcentaje",
            "descuento_monto",
            "impuesto_monto",
        ])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('facturacion', '0065_comprainventario_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacomprainventario',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lineacomprainventario',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lineacomprainventario',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoimpuesto'),
        ),
        migrations.AddField(
            model_name='lineacomprainventario',
            name='impuesto_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lineacomprainventario',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineacomprainventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.RunPython(backfill_totales_lineas_compra, migrations.RunPython.noop),
    ]
