# Generated by Django 5.2.12 on 2026-07-31 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_unique_asiento_evento_documento_empresa'),
        ('facturacion', '0066_lineacomprainventario_descuento_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainventario',
            name='cuenta_financiera_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_contado', to='contabilidad.cuentafinanciera'),
        ),
    ]
