# Generated by Django 5.2.12 on 2026-08-17 22:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_unique_asiento_evento_documento_empresa'),
        ('facturacion', '0068_pagofactura_comision_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComisionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comision_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_comision_proveedor', to='facturacion.pagofactura')),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comisiones_proveedores', to='contabilidad.cuentafinanciera')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_comisiones_proveedores_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
