# Generated by Django 5.2.12 on 2026-08-25 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0070_inicializar_lotes_fefo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientolotebodega',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_lote_bodega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('entrada_compra', 'Entrada por Compra'), ('salida_factura', 'Salida por Factura'), ('devolucion_nota_credito', 'Entrada por Nota de Credito'), ('ajuste_entrada', 'Ajuste Positivo'), ('ajuste_salida', 'Ajuste Negativo'), ('regalia', 'Regalia'), ('reversion_factura', 'Reversion de Factura'), ('reversion_nota_credito', 'Reversion de Nota de Credito'), ('reversion_compra', 'Reversion de Compra')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientolotebodega',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida_factura', 'Salida por factura'), ('traslado_salida', 'Traslado salida'), ('traslado_entrada', 'Traslado entrada'), ('ajuste', 'Ajuste'), ('regalia', 'Regalia'), ('reversion', 'Reversion')], max_length=30),
        ),
    ]
