# Generated by Django 5.2.12 on 2026-09-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_unique_asiento_evento_documento_empresa'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        ('facturacion', '0071_movimientoinventario_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_fiscales_capturadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='identidad_captura',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='numero_factura_normalizado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='registrocomprafiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'identidad_captura', 'numero_factura_normalizado'), name='unique_compra_captura_rapida'),
        ),
    ]
