# Generated by Django 5.2.12 on 2026-09-09 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_unique_asiento_evento_documento_empresa'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        ('facturacion', '0073_libro_compra_mensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('rtn', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='librocompramensual',
            name='unique_libro_compra_mes',
        ),
        migrations.RemoveConstraint(
            model_name='registrocomprafiscal',
            name='unique_compra_captura_rapida',
        ),
        migrations.AddField(
            model_name='clientecontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contables', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='clientecontable',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='clientes_contables_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librocompramensual',
            name='cliente_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libros_compras', to='facturacion.clientecontable'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cliente_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='facturacion.clientecontable'),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='cliente_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_fiscales', to='facturacion.clientecontable'),
        ),
        migrations.AddConstraint(
            model_name='librocompramensual',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente_contable__isnull', True)), fields=('empresa', 'anio', 'mes'), name='unique_libro_compra_mes'),
        ),
        migrations.AddConstraint(
            model_name='librocompramensual',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente_contable', 'anio', 'mes'), name='unique_libro_cliente_mes'),
        ),
        migrations.AddConstraint(
            model_name='registrocomprafiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente_contable__isnull', True)), fields=('empresa', 'identidad_captura', 'numero_factura_normalizado'), name='unique_compra_captura_rapida'),
        ),
        migrations.AddConstraint(
            model_name='registrocomprafiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente_contable', 'identidad_captura', 'numero_factura_normalizado'), name='unique_compra_cliente_captura'),
        ),
        migrations.AddConstraint(
            model_name='clientecontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_cliente_contable_nombre'),
        ),
    ]
