# Generated by Django 5.2.12 on 2026-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0075_clientes_iniciales_dubon'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='clave_importacion',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrocomprafiscal',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
