# Generated by Django 5.2.12 on 2026-09-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0076_importacion_historica_clientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='clasificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='clasificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_clasificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CuentaAcumuladoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.CharField(choices=[('costo', 'Costo de producción y venta'), ('gasto', 'Gastos de operación y administración'), ('financiero', 'Gastos financieros')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=100)),
                ('activa', models.BooleanField(default=True)),
                ('cliente_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_acumulado', to='facturacion.clientecontable')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='cuenta_acumulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='facturacion.cuentaacumuladocompra'),
        ),
        migrations.AddConstraint(
            model_name='cuentaacumuladocompra',
            constraint=models.UniqueConstraint(fields=('cliente_contable', 'nombre'), name='unique_cuenta_acumulado_cliente'),
        ),
    ]
