# Generated by Django 5.2.12 on 2026-09-14 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0078_cuentas_referencia_nordic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_habitual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_habituales', to='facturacion.cuentaacumuladocompra', verbose_name='Cuenta contable habitual'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_habitual_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_habitual_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_habituales_configuradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='proveedor_vinculado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrocomprafiscal',
            name='proveedor_vinculado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_compras_vinculados', to=settings.AUTH_USER_MODEL),
        ),
    ]
