# Generated by Django 5.2.12 on 2026-04-13 02:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_rolsistema_puede_configuracion_rrhh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRRHHEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihss_trabajador_porcentaje', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), max_digits=6)),
                ('ihss_techo_mensual', models.DecimalField(decimal_places=2, default=Decimal('11903.13'), max_digits=12)),
                ('rap_trabajador_porcentaje', models.DecimalField(decimal_places=4, default=Decimal('0.0150'), max_digits=6)),
                ('aplicar_rap', models.BooleanField(default=True)),
                ('isr_porcentaje_base', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('moneda', models.CharField(default='HNL', max_length=10)),
                ('hora_extra_diurna_factor', models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=5)),
                ('hora_extra_nocturna_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('hora_extra_feriado_factor', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('dias_base_mes', models.PositiveIntegerField(default=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_rrhh', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion de RRHH',
                'verbose_name_plural': 'Configuraciones de RRHH',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('identidad', models.CharField(blank=True, max_length=25, null=True)),
                ('rtn', models.CharField(blank=True, max_length=25, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='rrhh/empleados/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('puesto', models.CharField(blank=True, max_length=120, null=True)),
                ('departamento', models.CharField(blank=True, max_length=120, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_salario', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('diario', 'Diario')], default='mensual', max_length=20)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=80, null=True)),
                ('banco', models.CharField(blank=True, max_length=120, null=True)),
                ('aplica_ihss', models.BooleanField(default=True)),
                ('aplica_rap', models.BooleanField(default=True)),
                ('aplica_isr', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('retirado', 'Retirado')], default='activo', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
            ],
            options={
                'ordering': ['nombres', 'apellidos'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal'), ('especial', 'Especial')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('incluir_14avo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('calculada', 'Calculada'), ('cerrada', 'Cerrada'), ('pagada', 'Pagada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_planilla', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bono', 'Bono'), ('comision', 'Comision'), ('deduccion', 'Deduccion'), ('prestamo', 'Prestamo')], max_length=20)),
                ('descripcion', models.CharField(max_length=160)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('aplicado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_planilla', to='rrhh.empleado')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='rrhh.periodoplanilla')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VacacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='rrhh.empleado')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_pagados', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_extra_diurnas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_extra_nocturnas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('horas_extra_feriado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decimo_cuarto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ihss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prestamos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_planilla', to='rrhh.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rrhh.periodoplanilla')),
            ],
            options={
                'ordering': ['empleado__nombres', 'empleado__apellidos'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
