# Generated by Django 5.2.12 on 2026-06-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_asientocontable_unique_asiento_evento_documento_empresa'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoplanilla',
            name='cuenta_financiera_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planillas_pagadas', to='contabilidad.cuentafinanciera'),
        ),
    ]
