# Generated by Django 5.2.12 on 2026-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_13avo_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoplanilla',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20),
        ),
    ]
