# Generated by Django 5.2.12 on 2026-04-10 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0011_modulo_contabilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='documento_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='documento_tipo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='evento',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['empresa', 'documento_tipo', 'documento_id', 'evento'], name='contabilida_empresa_302297_idx'),
        ),
    ]
