# Generated by Django 5.2.12 on 2026-04-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_asientocontable_documento_id_and_more'),
        ('core', '0011_modulo_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContableEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_bancos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_bancos', to='contabilidad.cuentacontable')),
                ('cuenta_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_caja', to='contabilidad.cuentacontable')),
                ('cuenta_clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_clientes', to='contabilidad.cuentacontable')),
                ('cuenta_devoluciones_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_devoluciones_ventas', to='contabilidad.cuentacontable')),
                ('cuenta_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_inventario', to='contabilidad.cuentacontable')),
                ('cuenta_isv_por_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_isv_por_pagar', to='contabilidad.cuentacontable')),
                ('cuenta_proveedores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_proveedores', to='contabilidad.cuentacontable')),
                ('cuenta_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_ventas', to='contabilidad.cuentacontable')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_contable', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion contable por empresa',
                'verbose_name_plural': 'Configuraciones contables por empresa',
            },
        ),
    ]
