# Generated by Django 5.2.12 on 2026-04-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_configuracioncontableempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='contabilidad.cuentacontable'),
        ),
    ]
