# Generated by Django 5.2.12 on 2026-04-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_cuentacontable_cuenta_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('costo', 'Costo'), ('gasto', 'Gasto')], max_length=20),
        ),
    ]
