# Generated by Django 5.2.12 on 2026-04-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_periodocontable'),
        ('core', '0011_modulo_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCompraFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_compras_fiscales', to='contabilidad.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_compras_fiscales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Clasificacion de compra fiscal',
                'verbose_name_plural': 'Clasificaciones de compras fiscales',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
