# Generated by Django 5.2.12 on 2026-04-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_clasificacioncomprafiscal'),
        ('core', '0011_modulo_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionMovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('transferencia', 'Transferencia')], default='egreso', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones_movimientos_banco', to='contabilidad.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_movimientos_banco', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('tarjeta_credito', 'Tarjeta de credito')], default='banco', max_length=30)),
                ('institucion', models.CharField(blank=True, max_length=160, null=True)),
                ('numero', models.CharField(blank=True, max_length=80, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_financieras', to='contabilidad.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_financieras', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('clasificado', 'Clasificado'), ('contabilizado', 'Contabilizado')], default='pendiente', max_length=20)),
                ('origen_importacion', models.CharField(blank=True, max_length=160, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='contabilidad.asientocontable')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='contabilidad.clasificacionmovimientobanco')),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.cuentafinanciera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empresa', 'cuenta_financiera', 'fecha'], name='contabilida_empresa_3fa285_idx')],
            },
        ),
    ]
