# Generated by Django 5.2.12 on 2026-04-11 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_clasificacionmovimientobanco_cuentafinanciera_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='conciliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios_conciliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
