# Generated by Django 5.2.12 on 2026-04-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_movimientobancario_conciliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncontableempresa',
            name='cuenta_compras_fiscales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_compras_fiscales', to='contabilidad.cuentacontable'),
        ),
        migrations.AddField(
            model_name='configuracioncontableempresa',
            name='cuenta_isv_acreditable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_isv_acreditable', to='contabilidad.cuentacontable'),
        ),
    ]
