# Generated by Django 5.2.12 on 2026-04-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_configuracioncontableempresa_cuenta_compras_fiscales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncontableempresa',
            name='cuenta_compras_fiscales',
        ),
        migrations.RemoveField(
            model_name='configuracioncontableempresa',
            name='cuenta_isv_acreditable',
        ),
    ]
