# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0011_remove_configuracioncontableempresa_cuenta_compras_fiscales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentafinanciera",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("caja", "Caja"),
                    ("banco", "Banco"),
                    ("tarjeta_credito", "Tarjeta de credito"),
                ],
                default="banco",
                max_length=30,
            ),
        ),
    ]
