# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0012_alter_cuentafinanciera_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaClasificacionBanco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=140)),
                ("texto_busqueda", models.CharField(max_length=160)),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("todos", "Todos"),
                            ("ingreso", "Solo ingresos"),
                            ("egreso", "Solo egresos"),
                        ],
                        default="todos",
                        max_length=20,
                    ),
                ),
                ("prioridad", models.PositiveIntegerField(default=100)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "clasificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglas_bancarias",
                        to="contabilidad.clasificacionmovimientobanco",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_clasificacion_banco",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["prioridad", "nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
    ]
