# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0013_reglaclasificacionbanco"),
        ("facturacion", "0028_configuracionfacturacionempresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="pago_factura",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimiento_bancario",
                to="facturacion.pagofactura",
            ),
        ),
    ]
