# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0029_pagocompra_cuenta_financiera"),
        ("contabilidad", "0014_movimientobancario_pago_factura"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="pago_compra",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimiento_bancario",
                to="facturacion.pagocompra",
            ),
        ),
    ]
