# Generated by Django 5.2.12 on 2026-04-21 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_movimientobancario_pago_compra'),
        ('core', '0015_configuracionavanzadaempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False), models.Q(('numero__exact', ''), _negated=True)), fields=('empresa', 'numero'), name='unique_asiento_numero_por_empresa'),
        ),
    ]
