# Generated by Django 5.2.12 on 2026-06-19 15:55

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


CUENTAS_CORRECTAS = {
    'cuenta_bancos': ('110201', 'Banco Moneda Nacional', 'activo'),
    'cuenta_clientes': ('111001', 'Clientes Nacionales', 'activo'),
    'cuenta_inventario': ('112001', 'Inventario de Mercaderia', 'activo'),
    'cuenta_isv_por_pagar': ('210201', 'ISV Cobrado 15%', 'pasivo'),
    'cuenta_proveedores': ('210101', 'Proveedores Nacionales', 'pasivo'),
    'cuenta_ventas': ('410101', 'Ventas Gravadas 15%', 'ingreso'),
    'cuenta_devoluciones_ventas': ('410202', 'Devoluciones sobre Ventas', 'ingreso'),
}

CODIGOS_ANTIGUOS = {
    'cuenta_bancos': {'1102'},
    'cuenta_clientes': {'1110'},
    'cuenta_inventario': {'1120', '1140'},
    'cuenta_isv_por_pagar': {'2102'},
    'cuenta_proveedores': {'2101'},
    'cuenta_ventas': {'4101'},
    'cuenta_devoluciones_ventas': {'4102', '5101'},
}


def preparar_integridad_contable(apps, schema_editor):
    Asiento = apps.get_model('contabilidad', 'AsientoContable')
    Cuenta = apps.get_model('contabilidad', 'CuentaContable')
    Configuracion = apps.get_model('contabilidad', 'ConfiguracionContableEmpresa')

    duplicados = (
        Asiento.objects.exclude(documento_id__isnull=True)
        .exclude(documento_tipo='')
        .exclude(evento='')
        .values('empresa_id', 'documento_tipo', 'documento_id', 'evento')
        .annotate(cantidad=Count('id'))
        .filter(cantidad__gt=1)
    )
    for grupo in duplicados.iterator():
        ids = list(
            Asiento.objects.filter(
                empresa_id=grupo['empresa_id'],
                documento_tipo=grupo['documento_tipo'],
                documento_id=grupo['documento_id'],
                evento=grupo['evento'],
            ).order_by('id').values_list('id', flat=True)
        )
        Asiento.objects.filter(id__in=ids[1:]).delete()

    for configuracion in Configuracion.objects.all().iterator():
        cambios = []
        for campo, (codigo, nombre, tipo) in CUENTAS_CORRECTAS.items():
            cuenta_actual = getattr(configuracion, campo)
            if cuenta_actual and cuenta_actual.codigo not in CODIGOS_ANTIGUOS[campo]:
                continue
            cuenta, _ = Cuenta.objects.get_or_create(
                empresa_id=configuracion.empresa_id,
                codigo=codigo,
                defaults={
                    'nombre': nombre,
                    'tipo': tipo,
                    'acepta_movimientos': True,
                    'activa': True,
                },
            )
            actualizaciones = {}
            if not cuenta.activa:
                actualizaciones['activa'] = True
            if not cuenta.acepta_movimientos:
                actualizaciones['acepta_movimientos'] = True
            if actualizaciones:
                Cuenta.objects.filter(pk=cuenta.pk).update(**actualizaciones)
            setattr(configuracion, campo, cuenta)
            cambios.append(campo)
        if cambios:
            configuracion.save(update_fields=cambios)


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_asientocontable_unique_asiento_numero_por_empresa'),
        ('core', '0030_permisos_configuracion_y_cierres_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preparar_integridad_contable, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_id__isnull', False), models.Q(('documento_tipo__exact', ''), _negated=True), models.Q(('evento__exact', ''), _negated=True)), fields=('empresa', 'documento_tipo', 'documento_id', 'evento'), name='unique_asiento_evento_documento_empresa'),
        ),
    ]
