# Generated by Django 5.2.12 on 2026-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_configuracioncrm_marketing_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
