# Generated by Django 5.2.12 on 2026-06-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_historiaclinicaespecialidad_datos_especialidad_and_more'),
        ('crm', '0005_citacliente_duracion_minutos'),
        ('facturacion', '0052_lineafactura_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_agenda', to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='profesional_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agenda', to='clinica.profesionalsalud'),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='servicio_clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agenda', to='clinica.servicioclinico'),
        ),
        migrations.AlterField(
            model_name='citacliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='facturacion.cliente'),
        ),
    ]
