# Generated by Django 5.2.12 on 2026-06-22 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_historiaclinicaespecialidad_datos_especialidad_and_more'),
        ('crm', '0006_citacliente_paciente_citacliente_profesional_salud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='cita_clinica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_agenda', to='clinica.citaclinica'),
        ),
    ]
