# Generated by Django 5.2.12 on 2026-06-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_citacliente_cita_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='enviar_confirmacion_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='recordatorio_dia_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='recordatorio_semana_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='whatsapp_idioma_cita',
            field=models.CharField(default='es', max_length=12),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='whatsapp_plantilla_cita',
            field=models.CharField(default='recordatorio_cita', max_length=80),
        ),
        migrations.CreateModel(
            name='NotificacionCitaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación al crear'), ('semana', 'Recordatorio 7 días antes'), ('dia', 'Recordatorio 1 día antes')], max_length=20)),
                ('programada_para', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error'), ('omitido', 'Omitido')], db_index=True, default='pendiente', max_length=15)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_whatsapp', to='crm.citacliente')),
            ],
            options={
                'ordering': ['programada_para', 'id'],
                'constraints': [models.UniqueConstraint(fields=('cita', 'tipo'), name='unique_notificacion_tipo_por_cita')],
            },
        ),
    ]
