# Generated by Django 5.2.12 on 2026-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_citacliente_enviar_confirmacion_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncrm',
            name='whatsapp_cita_incluir_enlace',
            field=models.BooleanField(default=False),
        ),
    ]
