# Generated by Django 5.2.12 on 2026-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_configuracioncrm_whatsapp_cita_incluir_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
