# Generated by Django 5.2.12 on 2026-07-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_citacliente_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncrm',
            name='whatsapp_idioma_preconsulta',
            field=models.CharField(default='es', max_length=12),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='whatsapp_plantilla_preconsulta',
            field=models.CharField(default='preconsulta_paciente', max_length=80),
        ),
    ]
