# Generated by Django 5.2.12 on 2026-07-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rol_eliminar_facturas_emitidas'),
        ('crm', '0011_configuracioncrm_whatsapp_idioma_preconsulta_and_more'),
        ('facturacion', '0060_promocionpuntoventa_productopromocionpuntoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncrm',
            name='cumpleanos_recordatorio_1_dia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='cumpleanos_recordatorio_7_dias',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificacionCumpleanosWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antes', models.PositiveSmallIntegerField(default=1)),
                ('cumpleanos_fecha', models.DateField(db_index=True)),
                ('programada_para', models.DateTimeField(db_index=True)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error'), ('omitido', 'Omitido')], db_index=True, default='pendiente', max_length=15)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cumpleanos_whatsapp', to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cumpleanos_whatsapp', to='core.empresa')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.plantillamensaje')),
            ],
            options={
                'ordering': ['programada_para', 'cliente__nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cliente', 'dias_antes', 'cumpleanos_fecha'), name='unique_notificacion_cumpleanos_cliente_fecha')],
            },
        ),
    ]
