# Generated by Django 5.2.12 on 2026-07-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_configuracioncrm_cumpleanos_recordatorio_1_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncrm',
            name='mensaje_cita_cancelada',
            field=models.TextField(default='cita cancelada'),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='mensaje_cita_confirmacion',
            field=models.TextField(default='confirmacion de cita'),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='mensaje_cita_reagendada',
            field=models.TextField(default='cita reagendada'),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='mensaje_cita_recordatorio_1_dia',
            field=models.TextField(default='recordatorio: su cita es manana'),
        ),
        migrations.AddField(
            model_name='configuracioncrm',
            name='mensaje_cita_recordatorio_7_dias',
            field=models.TextField(default='recordatorio: falta una semana'),
        ),
    ]
