# Generated by Django 5.2.12 on 2026-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_cita_cirugia_serviciosmedicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacirugiafoto',
            name='imagen',
            field=models.FileField(upload_to='crm/citas/cirugias/'),
        ),
    ]
