# Generated by Django 5.2.12 on 2026-08-13 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_usuario_retiro_control'),
        ('crm', '0015_alter_citacirugiafoto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citacliente',
            name='fase_servicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='grupo_atencion',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='opcion_servicio',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='citacliente',
            name='sesion_servicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpcionServicioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('tratamientos', 'Tratamientos'), ('spa', 'Spa')], max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opciones_servicio_agenda_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_servicio_agenda', to='core.empresa')),
            ],
            options={
                'ordering': ['categoria', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'categoria', 'nombre'), name='crm_opcion_agenda_empresa_categoria_nombre_uniq')],
            },
        ),
    ]
