# Generated by Django 5.2.12 on 2026-08-21 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0023_invitacionregistropaciente_trazabilidad'),
        ('core', '0044_acciones_onix'),
        ('crm', '0017_configurar_detalles_agenda_hospital_mia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaCamaraHiperbarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugia', models.CharField(blank=True, max_length=220)),
                ('fecha_cirugia', models.DateField(blank=True, null=True)),
                ('indicacion', models.TextField(blank=True)),
                ('programa', models.CharField(blank=True, choices=[('10x90', '10 sesiones de 90 minutos'), ('20x45', '20 sesiones de 45 minutos'), ('otro', 'Otro programa')], max_length=20)),
                ('programa_otro', models.CharField(blank=True, max_length=180)),
                ('orden_medica', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_camara_hiperbarica_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_camara_hiperbarica_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_camara_hiperbarica', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_camara_hiperbarica', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Programa de cámara hiperbárica',
                'verbose_name_plural': 'Programas de cámara hiperbárica',
                'ordering': ['-activo', '-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionCamaraHiperbarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveSmallIntegerField()),
                ('fecha_sesion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado_general_estable', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sin_fiebre', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sin_dificultad_respiratoria', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sin_dolor_toracico', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sin_sintomas_neurologicos', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('sin_dolor_oido', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('compensa_ambos_oidos', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('area_quirurgica_revisada', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('seguridad_camara_verificada', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('apto_para_sesion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('observaciones_previas', models.TextField(blank=True)),
                ('firma_control_previo', models.CharField(blank=True, max_length=180)),
                ('presion_arterial_antes', models.CharField(blank=True, max_length=30)),
                ('saturacion_oxigeno_antes', models.CharField(blank=True, max_length=20)),
                ('presion_camara', models.CharField(blank=True, max_length=30)),
                ('tiempo_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compensacion_oidos', models.CharField(blank=True, max_length=180)),
                ('tolerancia', models.CharField(blank=True, choices=[('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=12)),
                ('presion_arterial_despues', models.CharField(blank=True, max_length=30)),
                ('saturacion_oxigeno_despues', models.CharField(blank=True, max_length=20)),
                ('evolucion_evento_adverso', models.TextField(blank=True)),
                ('firma_parametros', models.CharField(blank=True, max_length=180)),
                ('nota_enfermeria', models.TextField(blank=True)),
                ('firma_enfermeria', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Sesión finalizada')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_camara_hiperbarica_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_camara_hiperbarica', to='crm.citacliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_camara_hiperbarica_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_camara_hiperbarica', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_camara_hiperbarica', to='clinica.paciente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='crm.programacamarahiperbarica')),
            ],
            options={
                'verbose_name': 'Sesión de cámara hiperbárica',
                'verbose_name_plural': 'Sesiones de cámara hiperbárica',
                'ordering': ['numero_sesion', 'fecha_sesion', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='programacamarahiperbarica',
            index=models.Index(fields=['empresa', 'paciente', 'activo'], name='crm_program_empresa_6ce283_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncamarahiperbarica',
            index=models.Index(fields=['empresa', 'paciente', 'estado'], name='crm_sesionc_empresa_ec0f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncamarahiperbarica',
            constraint=models.UniqueConstraint(fields=('programa', 'numero_sesion'), name='crm_camara_programa_numero_sesion_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sesioncamarahiperbarica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion__gte', 1), ('numero_sesion__lte', 22)), name='crm_camara_numero_sesion_1_22'),
        ),
    ]
