# Generated by Django 5.2.12 on 2026-08-24 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0024_alter_historiaclinicaespecialidad_tipo_and_more'),
        ('core', '0044_acciones_onix'),
        ('crm', '0018_programacamarahiperbarica_sesioncamarahiperbarica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaTerapiaPostQuirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugia', models.CharField(blank=True, max_length=220)),
                ('fecha_cirugia', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_terapia_postquirurgica_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_terapia_postquirurgica_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_terapia_postquirurgica', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_terapia_postquirurgica', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Programa de terapias post quirúrgicas',
                'verbose_name_plural': 'Programas de terapias post quirúrgicas',
                'ordering': ['-activo', '-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionTerapiaPostQuirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveSmallIntegerField()),
                ('fecha_sesion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=30)),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=20)),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=20)),
                ('saturacion_oxigeno', models.CharField(blank=True, max_length=20)),
                ('temperatura', models.CharField(blank=True, max_length=20)),
                ('escala_dolor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado_paciente', models.JSONField(blank=True, default=list)),
                ('equipos_utilizados', models.JSONField(blank=True, default=list)),
                ('minutos_area', models.CharField(blank=True, max_length=180)),
                ('cuidados_realizados', models.JSONField(blank=True, default=list)),
                ('cuidado_otro', models.CharField(blank=True, max_length=220)),
                ('nota_enfermeria', models.TextField(blank=True)),
                ('enfermera_nombre', models.CharField(blank=True, max_length=180)),
                ('firma_enfermeria', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Sesión finalizada')], default='borrador', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_terapia_postquirurgica_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_terapia_postquirurgica', to='crm.citacliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_terapia_postquirurgica_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_terapia_postquirurgica', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_terapia_postquirurgica', to='clinica.paciente')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='crm.programaterapiapostquirurgica')),
            ],
            options={
                'verbose_name': 'Sesión de terapia post quirúrgica',
                'verbose_name_plural': 'Sesiones de terapia post quirúrgica',
                'ordering': ['numero_sesion', 'fecha_sesion', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='programaterapiapostquirurgica',
            index=models.Index(fields=['empresa', 'paciente', 'activo'], name='crm_program_empresa_70017c_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionterapiapostquirurgica',
            index=models.Index(fields=['empresa', 'paciente', 'estado'], name='crm_sesiont_empresa_3490b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.UniqueConstraint(fields=('programa', 'numero_sesion'), name='crm_terapia_post_programa_sesion_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion__gte', 1), ('numero_sesion__lte', 12)), name='crm_terapia_post_sesion_1_12'),
        ),
    ]
