# Generated by Django 5.2.12 on 2026-09-01 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0026_alter_historiaclinicaespecialidad_tipo_and_more'),
        ('core', '0049_habilitar_rrhh_clinicas_solicitadas'),
        ('crm', '0019_programaterapiapostquirurgica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncamarahiperbarica',
            name='numero_sesion_adicional',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionterapiapostquirurgica',
            name='numero_sesion_adicional',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sesioncamarahiperbarica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion_adicional__isnull', True), models.Q(('numero_sesion_adicional__gte', 1), ('numero_sesion_adicional__lte', 22), models.Q(('numero_sesion_adicional', models.F('numero_sesion')), _negated=True)), _connector='OR'), name='crm_camara_sesion_adicional_valida'),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion_adicional__isnull', True), models.Q(('numero_sesion_adicional__gte', 1), ('numero_sesion_adicional__lte', 12), models.Q(('numero_sesion_adicional', models.F('numero_sesion')), _negated=True)), _connector='OR'), name='crm_terapia_post_sesion_adicional_valida'),
        ),
    ]
