# Generated by Django 5.2.12 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_sesioncamarahiperbarica_numero_sesion_adicional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citacliente",
            name="cortesia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="citacliente",
            constraint=models.CheckConstraint(
                condition=models.Q(("cortesia", True), ("pagada", True), _negated=True),
                name="crm_cita_no_pagada_y_cortesia",
            ),
        ),
    ]
