# Generated by Django 5.2.12 on 2026-09-14 16:08

from django.conf import settings
from django.db import migrations, models


def conservar_fase_desde_cita(apps, schema_editor):
    Sesion = apps.get_model("crm", "SesionTerapiaPostQuirurgica")
    for sesion in Sesion.objects.select_related("cita").filter(cita__fase_servicio__in=[1, 2]).iterator():
        sesion.fase = sesion.cita.fase_servicio
        sesion.save(update_fields=["fase"])


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0030_citaclinica_cortesia'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        ('crm', '0021_citacliente_cortesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sesionterapiapostquirurgica',
            name='crm_terapia_post_programa_sesion_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='sesionterapiapostquirurgica',
            name='crm_terapia_post_sesion_1_12',
        ),
        migrations.RemoveConstraint(
            model_name='sesionterapiapostquirurgica',
            name='crm_terapia_post_sesion_adicional_valida',
        ),
        migrations.AddField(
            model_name='programaterapiapostquirurgica',
            name='sesiones_habilitadas',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sesionterapiapostquirurgica',
            name='fase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2')], default=1),
        ),
        migrations.RunPython(conservar_fase_desde_cita, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sesionterapiapostquirurgica',
            name='numero_sesion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sesionterapiapostquirurgica',
            name='numero_sesion_adicional',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.UniqueConstraint(fields=('programa', 'fase', 'numero_sesion'), name='crm_terapia_post_programa_fase_sesion_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion__gte', 1)), name='crm_terapia_post_sesion_positiva'),
        ),
        migrations.AddConstraint(
            model_name='sesionterapiapostquirurgica',
            constraint=models.CheckConstraint(condition=models.Q(('numero_sesion_adicional__isnull', True), models.Q(('numero_sesion_adicional__gte', 1), models.Q(('numero_sesion_adicional', models.F('numero_sesion')), _negated=True)), _connector='OR'), name='crm_terapia_post_sesion_adicional_positiva'),
        ),
    ]
