# Generated by Django 5.2.12 on 2026-09-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0030_citaclinica_cortesia"),
        ("crm", "0024_configuracioncrm_whatsapp_numero_conectado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueoDisponibilidadMedica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("dia_completo", models.BooleanField(default=False)),
                ("motivo", models.CharField(blank=True, max_length=220)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("creado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bloqueos_disponibilidad_creados", to=settings.AUTH_USER_MODEL)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bloqueos_disponibilidad_medica", to="core.empresa")),
                ("profesional", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bloqueos_disponibilidad", to="clinica.profesionalsalud")),
            ],
            options={
                "verbose_name": "Bloqueo de disponibilidad médica",
                "verbose_name_plural": "Bloqueos de disponibilidad médica",
                "ordering": ["fecha", "hora_inicio", "profesional__nombre"],
                "indexes": [
                    models.Index(fields=["empresa", "fecha"], name="crm_bloq_empresa_fecha"),
                    models.Index(fields=["profesional", "fecha"], name="crm_bloq_prof_fecha"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("dia_completo", True),
                            models.Q(
                                ("hora_inicio__isnull", False),
                                ("hora_fin__isnull", False),
                                ("hora_fin__gt", models.F("hora_inicio")),
                            ),
                            _connector="OR",
                        ),
                        name="crm_bloqueo_horario_valido",
                    ),
                ],
            },
        ),
    ]
