# Generated by Django 5.2.12 on 2026-06-06 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_rolsistema_puede_clinica_and_more'),
        ('facturacion', '0043_recibopago_concepto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Unidad Clinica', max_length=180)),
                ('especialidad_principal', models.CharField(default='Cirugia plastica y medicina estetica', max_length=140)),
                ('requiere_consentimiento_procedimientos', models.BooleanField(default=True)),
                ('alertas_postoperatorias_activas', models.BooleanField(default=True)),
                ('dias_alerta_cumpleanos', models.PositiveIntegerField(default=7)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_clinica', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuracion clinica',
                'verbose_name_plural': 'Configuraciones clinicas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_codigo', models.CharField(max_length=40)),
                ('identidad', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=160)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro'), ('no_indicado', 'No indicado')], default='no_indicado', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=180, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=30, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('notas_privadas', models.TextField(blank=True, null=True)),
                ('acepta_promociones', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_clinicos', to='facturacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'expediente_codigo')},
            },
        ),
        migrations.CreateModel(
            name='CitaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('en_atencion', 'En atencion'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistio')], default='solicitada', max_length=20)),
                ('canal', models.CharField(choices=[('recepcion', 'Recepcion'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telefono', 'Telefono'), ('referido', 'Referido'), ('otro', 'Otro')], default='recepcion', max_length=20)),
                ('motivo', models.CharField(max_length=220)),
                ('sala', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_clinicas', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Cita clinica',
                'verbose_name_plural': 'Citas clinicas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('especialidad', models.CharField(blank=True, max_length=140, null=True)),
                ('colegiacion', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_salud', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional de salud',
                'verbose_name_plural': 'Profesionales de salud',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('evaluacion', 'Evaluacion'), ('evolucion', 'Evolucion'), ('tratamiento', 'Tratamiento'), ('procedimiento', 'Procedimiento'), ('medicamento', 'Medicamento'), ('seguimiento', 'Seguimiento'), ('nota', 'Nota interna')], default='consulta', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('signos_vitales', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_expediente', to='clinica.citaclinica')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_expediente', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_expediente', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Evento de expediente',
                'verbose_name_plural': 'Eventos de expediente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='citaclinica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_clinicas', to='clinica.profesionalsalud'),
        ),
        migrations.CreateModel(
            name='ServicioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('consulta', 'Consulta'), ('procedimiento', 'Procedimiento'), ('cirugia', 'Cirugia'), ('tratamiento', 'Tratamiento'), ('control', 'Control'), ('laboratorio', 'Laboratorio'), ('imagen', 'Imagen')], default='consulta', max_length=30)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requiere_consentimiento', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_clinicos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Servicio clinico',
                'verbose_name_plural': 'Servicios clinicos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='citaclinica',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.servicioclinico'),
        ),
        migrations.CreateModel(
            name='TratamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('plan_clinico', models.TextField(blank=True, null=True)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_pacientes', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.profesionalsalud')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicioclinico')),
            ],
            options={
                'verbose_name': 'Tratamiento de paciente',
                'verbose_name_plural': 'Tratamientos de pacientes',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPostOperatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('tipo', models.CharField(default='Control postoperatorio', max_length=120)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('requiere_revision', 'Requiere revision'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('signos_alarma', models.TextField(blank=True, null=True)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_postoperatorios', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_postoperatorios', to='clinica.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_postoperatorios', to='clinica.tratamientopaciente')),
            ],
            options={
                'verbose_name': 'Seguimiento postoperatorio',
                'verbose_name_plural': 'Seguimientos postoperatorios',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoPrescrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=180)),
                ('dosis', models.CharField(max_length=120)),
                ('frecuencia', models.CharField(max_length=120)),
                ('duracion', models.CharField(blank=True, max_length=120, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_prescripcion', models.DateField(default=django.utils.timezone.localdate)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_prescritos', to='core.empresa')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='clinica.expedienteevento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_prescritos', to='clinica.paciente')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='clinica.tratamientopaciente')),
            ],
            options={
                'verbose_name': 'Medicamento prescrito',
                'verbose_name_plural': 'Medicamentos prescritos',
                'ordering': ['-fecha_prescripcion', 'medicamento'],
            },
        ),
        migrations.AddField(
            model_name='expedienteevento',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_expediente', to='clinica.tratamientopaciente'),
        ),
        migrations.CreateModel(
            name='ConsentimientoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('contenido', models.TextField()),
                ('firmado_por', models.CharField(blank=True, max_length=160, null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='clinica/consentimientos/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('revocado', 'Revocado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='clinica.citaclinica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_clinicos', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='clinica.paciente')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='clinica.tratamientopaciente')),
            ],
            options={
                'verbose_name': 'Consentimiento clinico',
                'verbose_name_plural': 'Consentimientos clinicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
