# Generated by Django 5.2.12 on 2026-06-09 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('core', '0023_modulo_clinica_medica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='acompanante_celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='acompanante_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='acompanante_nombre',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='acompanante_relacion',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('hijo', 'Hijo/a'), ('conyuge', 'Conyuge'), ('familiar', 'Familiar'), ('amigo', 'Amigo/a'), ('tutor', 'Tutor/a'), ('otro', 'Otro'), ('no_indicada', 'No indicada')], default='no_indicada', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='acompanante_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='barrio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='celular_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridad',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnica', 'Tecnica'), ('universitaria', 'Universitaria'), ('postgrado', 'Postgrado'), ('no_indicada', 'No indicada')], default='no_indicada', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Union libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('no_indicado', 'No indicado')], default='no_indicado', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='extranjero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clinica/pacientes/perfil/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('no_indicado', 'No indicado')], default='no_indicado', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(default='Honduras', max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otra_ocupacion',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.CharField(default='Honduras', max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pertenencia_etnica',
            field=models.CharField(choices=[('mestizo', 'Mestizo'), ('garifuna', 'Garifuna'), ('lenca', 'Lenca'), ('miskito', 'Miskito'), ('tolupan', 'Tolupan'), ('chorti', 'Chorti'), ('pech', 'Pech'), ('tawahka', 'Tawahka'), ('nahua', 'Nahua'), ('otra', 'Otra'), ('no_indicada', 'No indicada')], default='no_indicada', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prefijo_telefono',
            field=models.CharField(default='Honduras (+504)', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='procedencia',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='recibir_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_relacion',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('hijo', 'Hijo/a'), ('conyuge', 'Conyuge'), ('familiar', 'Familiar'), ('amigo', 'Amigo/a'), ('tutor', 'Tutor/a'), ('otro', 'Otro'), ('no_indicada', 'No indicada')], default='no_indicada', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rh',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_id',
            field=models.CharField(choices=[('cc', 'CC Cedula ciudadania'), ('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('rtn', 'RTN'), ('otro', 'Otro')], default='cc', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona_residencial',
            field=models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural'), ('no_indicada', 'No indicada')], default='urbana', max_length=20),
        ),
        migrations.CreateModel(
            name='PacienteFotoEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='clinica/pacientes/evolucion/')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('preoperatorio', 'Preoperatorio'), ('procedimiento', 'Procedimiento'), ('postoperatorio', 'Postoperatorio'), ('control', 'Control'), ('evolucion', 'Evolucion'), ('otro', 'Otro')], default='ingreso', max_length=20)),
                ('titulo', models.CharField(default='Foto de ingreso', max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evolucion_pacientes', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evolucion', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Foto de evolucion del paciente',
                'verbose_name_plural': 'Fotos de evolucion del paciente',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
