# Generated by Django 5.2.12 on 2026-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente_acompanante_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='es_alergico',
            field=models.BooleanField(default=False),
        ),
    ]
