# Generated by Django 5.2.12 on 2026-06-18 03:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_paciente_es_alergico'),
        ('core', '0027_activar_pos_empresas_medicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica')], max_length=30)),
                ('fecha_atencion', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('signos_vitales', models.TextField(blank=True)),
                ('evaluacion_clinica', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('procedimiento', models.TextField(blank=True)),
                ('plan_tratamiento', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas_especialidad', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_especialidad', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_especialidad', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Historia clinica por especialidad',
                'verbose_name_plural': 'Historias clinicas por especialidad',
                'ordering': ['-fecha_atencion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'paciente', 'tipo'], name='clinica_his_empresa_9b3e13_idx'), models.Index(fields=['empresa', 'fecha_atencion'], name='clinica_his_empresa_b69fcb_idx')],
            },
        ),
    ]
