# Generated by Django 5.2.12 on 2026-06-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_historiaclinicaespecialidad'),
        ('core', '0027_activar_pos_empresas_medicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='datos_especialidad',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PreconsultaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_preview', models.CharField(max_length=16)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('revocada', 'Revocada')], default='pendiente', max_length=20)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('datos_generales', models.JSONField(blank=True, default=dict)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('funciones_organicas', models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterada', 'Alterada')], max_length=20)),
                ('funciones_detalle', models.TextField(blank=True)),
                ('revision_sistemas', models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterada', 'Alterada')], max_length=20)),
                ('revision_sistemas_detalle', models.TextField(blank=True)),
                ('antecedentes_hospitalarios', models.BooleanField(default=False)),
                ('antecedentes_hospitalarios_detalle', models.TextField(blank=True)),
                ('antecedentes_personales', models.JSONField(blank=True, default=list)),
                ('antecedentes_personales_detalle', models.TextField(blank=True)),
                ('medicamentos_habituales', models.JSONField(blank=True, default=list)),
                ('medicamentos_habituales_detalle', models.TextField(blank=True)),
                ('antecedentes_familiares', models.JSONField(blank=True, default=list)),
                ('antecedentes_familiares_detalle', models.TextField(blank=True)),
                ('dieta', models.TextField(blank=True)),
                ('ejercicio', models.TextField(blank=True)),
                ('habitos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('antecedentes_infecciosos', models.TextField(blank=True)),
                ('consentimiento_datos', models.BooleanField(default=False)),
                ('ip_completada', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preconsultas_clinicas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconsultas_clinicas', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconsultas', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Preconsulta clinica',
                'verbose_name_plural': 'Preconsultas clinicas',
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'paciente', 'estado'], name='clinica_pre_empresa_d517ef_idx'), models.Index(fields=['empresa', 'fecha_creacion'], name='clinica_pre_empresa_e3f3b3_idx')],
            },
        ),
    ]
