# Generated by Django 5.2.12 on 2026-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_historiaclinicaespecialidad_datos_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioclinico',
            name='categoria',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('procedimiento', 'Procedimiento'), ('cirugia', 'Cirugia'), ('tratamiento', 'Tratamiento'), ('spa', 'Faciales, masajes, hidrataciones, tratamientos esteticos no medicos'), ('control', 'Control'), ('laboratorio', 'Laboratorio'), ('imagen', 'Imagen')], default='consulta', max_length=30),
        ),
    ]
