# Generated by Django 5.2.12 on 2026-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_alter_servicioclinico_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicaespecialidad',
            name='tipo',
            field=models.CharField(choices=[('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Medicina Estetica'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica')], max_length=30),
        ),
    ]
