# Generated by Django 5.2.12 on 2026-07-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_preconsultaclinica_tipo_and_more'),
        ('core', '0036_rol_eliminar_facturas_emitidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionRegistroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_preview', models.CharField(max_length=16)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('revocada', 'Revocada')], default='pendiente', max_length=20)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('ip_completada', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_registro_paciente_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_registro_paciente', to='core.empresa')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_registro', to='clinica.paciente')),
                ('preconsulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_registro', to='clinica.preconsultaclinica')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'estado', 'fecha_expiracion'], name='clinica_inv_empresa_77d27c_idx')],
            },
        ),
    ]
