# Generated by Django 5.2.12 on 2026-07-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_backfill_clientes_hospital_mia_como_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='analisis_clinico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='conducta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='examen_fisico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='historia_enfermedad_actual',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinicaespecialidad',
            name='notas_privadas_doctor',
            field=models.TextField(blank=True),
        ),
    ]
