# Generated by Django 5.2.12 on 2026-07-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_historiaclinicaespecialidad_analisis_clinico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicaespecialidad',
            name='tipo',
            field=models.CharField(choices=[('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Tratamiento Estetico / Piel'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='preconsultaclinica',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Tratamiento Estetico / Piel'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica')], default='general', max_length=30),
        ),
    ]
