# Generated by Django 5.2.12 on 2026-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_alter_historiaclinicaespecialidad_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientefotoevolucion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='clinica/pacientes/evolucion/videos/'),
        ),
        migrations.AlterField(
            model_name='pacientefotoevolucion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clinica/pacientes/evolucion/'),
        ),
    ]
