# Generated by Django 5.2.12 on 2026-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_pacientefotoevolucion_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaclinica',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
