# Generated by Django 5.2.12 on 2026-07-11 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_citaclinica_pagada'),
        ('core', '0036_rol_eliminar_facturas_emitidas'),
        ('facturacion', '0060_promocionpuntoventa_productopromocionpuntoventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen / radiologia'), ('preoperatorio', 'Preoperatorio'), ('otro', 'Otro')], default='laboratorio', max_length=30)),
                ('fecha_examen', models.DateField(default=django.utils.timezone.localdate)),
                ('laboratorio', models.CharField(blank=True, max_length=180, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='clinica/examenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_pacientes', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='clinica.paciente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen de paciente',
                'verbose_name_plural': 'Examenes de pacientes',
                'ordering': ['-fecha_examen', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('diagnostico', models.CharField(blank=True, max_length=240, null=True)),
                ('indicaciones', models.TextField(help_text='Detalle libre de medicamentos, dosis, frecuencia, duracion e indicaciones.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_medicas', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='clinica.paciente')),
                ('productos', models.ManyToManyField(blank=True, related_name='recetas_clinicas', to='facturacion.producto')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_emitidas', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Receta medica',
                'verbose_name_plural': 'Recetas medicas',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
