# Generated by Django 5.2.12 on 2026-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_examenpaciente_recetamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconsultaclinica',
            name='funciones_organicas',
            field=models.CharField(blank=True, choices=[('no_aplica', 'No aplica'), ('normal', 'Normal'), ('alterada', 'Alterada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preconsultaclinica',
            name='revision_sistemas',
            field=models.CharField(blank=True, choices=[('no_aplica', 'No aplica'), ('normal', 'Normal'), ('alterada', 'Alterada')], max_length=20),
        ),
    ]
