# Generated by Django 5.2.12 on 2026-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0016_alter_preconsultaclinica_funciones_organicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaclinica',
            name='es_recordatorio_tratamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citaclinica',
            name='tratamiento_recordatorio',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
