# Generated by Django 5.2.12 on 2026-07-22 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_citaclinica_es_recordatorio_tratamiento_and_more'),
        ('core', '0037_modulo_cotizaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoClinicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('laboratorio', 'Trabajos de laboratorio'), ('radiologico', 'Solicitud estudio radiologico'), ('documento', 'Documentos'), ('remision', 'Remision y contraremision'), ('detalle_remision', 'Detalle remisiones'), ('incapacidad', 'Incapacidades')], max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate)),
                ('entidad', models.CharField(blank=True, max_length=180, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='clinica/documentos/')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos_pacientes', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_clinicos_emitidos', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Documento clinico de paciente',
                'verbose_name_plural': 'Documentos clinicos de pacientes',
                'ordering': ['-fecha_documento', '-fecha_creacion'],
            },
        ),
    ]
