# Generated by Django 5.2.12 on 2026-08-18 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0021_servicioclinico_color_calendario'),
        ('core', '0044_acciones_onix'),
        ('facturacion', '0069_pagocomisionproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('diagnostico', models.CharField(blank=True, max_length=240)),
                ('indicaciones_generales', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_recetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_recetas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de receta',
                'verbose_name_plural': 'Plantillas de recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaRecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_manual', models.CharField(blank=True, max_length=220)),
                ('cantidad', models.CharField(blank=True, max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clinica.plantillareceta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_plantillas_recetas', to='facturacion.producto')),
            ],
            options={
                'verbose_name': 'Detalle de plantilla de receta',
                'verbose_name_plural': 'Detalles de plantillas de recetas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_manual', models.CharField(blank=True, max_length=220)),
                ('cantidad', models.CharField(blank=True, max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_recetas_clinicas', to='facturacion.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_medicamentos', to='clinica.recetamedica')),
            ],
            options={
                'verbose_name': 'Detalle de receta medica',
                'verbose_name_plural': 'Detalles de recetas medicas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantillareceta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_plantilla_receta_empresa_nombre'),
        ),
    ]
