# Generated by Django 5.2.12 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0022_plantillareceta_plantillarecetadetalle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="cantidad_aperturas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="fecha_primera_apertura",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="fecha_ultima_actividad",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="fecha_ultimo_intento",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="intentos_envio",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="paso_maximo",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invitacionregistropaciente",
            name="ultimo_resultado",
            field=models.CharField(
                choices=[
                    ("sin_intento", "Sin intento de envio"),
                    ("validacion", "Detenido por validacion"),
                    ("error_tecnico", "Error tecnico"),
                    ("completado", "Completado"),
                ],
                default="sin_intento",
                max_length=20,
            ),
        ),
    ]
