# Generated by Django 5.2.12 on 2026-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0023_invitacionregistropaciente_trazabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicaespecialidad',
            name='tipo',
            field=models.CharField(choices=[('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Tratamiento Estetico / Piel'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica'), ('terapias_postquirurgicas', 'Terapias Post Quirurgicas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='preconsultaclinica',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('capilar', 'Capilar'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Tratamiento Estetico / Piel'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica'), ('terapias_postquirurgicas', 'Terapias Post Quirurgicas')], default='general', max_length=30),
        ),
    ]
