# Generated by Django 5.2.12 on 2026-09-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0025_ampliar_tipos_historia_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicaespecialidad',
            name='tipo',
            field=models.CharField(choices=[('evaluacion_integral', 'Evaluacion medica integral'), ('capilar', 'Capilar'), ('tricopigmentacion', 'Tricopigmentacion'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Medicina Estética'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica'), ('terapias_postquirurgicas', 'Terapias Post Quirurgicas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='preconsultaclinica',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('evaluacion_integral', 'Evaluacion medica integral'), ('capilar', 'Capilar'), ('tricopigmentacion', 'Tricopigmentacion'), ('cirugia_plastica', 'Cirugia plastica y reconstructiva'), ('medicina_estetica', 'Medicina Estética'), ('enfermeria', 'Enfermeria'), ('terapias', 'Terapias'), ('camara_hiperbarica', 'Camara hiperbarica'), ('terapias_postquirurgicas', 'Terapias Post Quirurgicas')], default='general', max_length=30),
        ),
    ]
