# Generated by Django 5.2.12 on 2026-09-11 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0026_alter_historiaclinicaespecialidad_tipo_and_more'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTratamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('profesional_nombre', models.CharField(blank=True, max_length=180)),
                ('autor_nombre', models.CharField(blank=True, max_length=180)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_tratamiento_clinico_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento_pacientes', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_tratamiento_creados', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Plan y tratamiento del paciente',
                'verbose_name_plural': 'Planes y tratamientos del paciente',
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['empresa', 'paciente', 'fecha_creacion'], name='clinica_pla_empresa_1af60c_idx')],
            },
        ),
    ]
