# Generated by Django 5.2.12 on 2026-09-11 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0027_plantratamientopaciente'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionAlopecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(choices=[('hamilton_norwood', 'Hamilton-Norwood'), ('ludwig', 'Ludwig')], max_length=30)),
                ('grado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('profesional_nombre', models.CharField(blank=True, max_length=180)),
                ('autor_nombre', models.CharField(blank=True, max_length=180)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_alopecia_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_alopecia', to='core.empresa')),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_alopecia', to='clinica.historiaclinicaespecialidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_alopecia', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_alopecia', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Clasificación de alopecia',
                'verbose_name_plural': 'Clasificaciones de alopecia',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empresa', 'paciente', 'fecha'], name='clinica_cla_empresa_8b8e85_idx'), models.Index(fields=['escala', 'grado'], name='clinica_cla_escala_f0d02d_idx')],
            },
        ),
    ]
