# Generated by Django 5.2.12 on 2026-09-13 16:55

import clinica.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0028_clasificacionalopecia'),
        ('core', '0050_permiso_cambiar_fecha_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to=clinica.models.manual_receta_upload_to)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuales_recetas_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuales_recetas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Manual de receta',
                'verbose_name_plural': 'Manuales de recetas',
                'ordering': ['titulo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='manuales',
            field=models.ManyToManyField(blank=True, related_name='recetas', to='clinica.manualreceta'),
        ),
    ]
