# Generated by Django 5.2.12 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0029_manualreceta_recetamedica_manuales"),
    ]

    operations = [
        migrations.AddField(
            model_name="citaclinica",
            name="cortesia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="citaclinica",
            constraint=models.CheckConstraint(
                condition=models.Q(("cortesia", True), ("pagada", True), _negated=True),
                name="clinica_cita_no_pagada_y_cortesia",
            ),
        ),
    ]
