# Generated by Django 5.2.12 on 2026-09-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0030_citaclinica_cortesia"),
        ("core", "0052_enfermera_manuales_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioManualPDF",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("canal", models.CharField(choices=[("whatsapp", "WhatsApp"), ("correo", "Correo")], max_length=20)),
                ("destinatario", models.CharField(max_length=254)),
                ("estado", models.CharField(choices=[("enviado", "Enviado"), ("parcial", "Envío parcial"), ("fallido", "Fallido")], default="enviado", max_length=20)),
                ("detalle_error", models.TextField(blank=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="envios_manuales_pdf", to="core.empresa")),
                ("enviado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="envios_manuales_pdf", to=settings.AUTH_USER_MODEL)),
                ("manuales", models.ManyToManyField(related_name="envios", to="clinica.manualreceta")),
                ("paciente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="envios_manuales_pdf", to="clinica.paciente")),
            ],
            options={
                "verbose_name": "Envío de manual PDF",
                "verbose_name_plural": "Envíos de manuales PDF",
                "ordering": ["-fecha_envio", "-id"],
            },
        ),
    ]
