# Generated by Django 5.2.12 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0031_enviomanualpdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enviomanualpdf",
            name="canal",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("whatsapp_manual", "WhatsApp Web"),
                    ("correo", "Correo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enviomanualpdf",
            name="estado",
            field=models.CharField(
                choices=[
                    ("preparado", "Preparado manualmente"),
                    ("enviado", "Enviado"),
                    ("parcial", "Envío parcial"),
                    ("fallido", "Fallido"),
                ],
                default="enviado",
                max_length=20,
            ),
        ),
    ]
