# Generated by Django 5.2.12 on 2026-09-25 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0032_alter_enviomanualpdf_canal_y_estado'),
        ('core', '0053_configurar_manuales_pdf_clinicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteAdicionalPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_adicionales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_adicionales_pacientes', to='core.empresa')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedente_adicional', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_adicionales_actualizados', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Antecedente adicional del paciente',
                'verbose_name_plural': 'Antecedentes adicionales de pacientes',
                'ordering': ['-fecha_actualizacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AntecedenteAdicionalHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_anterior', models.TextField(blank=True)),
                ('texto_nuevo', models.TextField(blank=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=180)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_antecedentes_adicionales', to='core.empresa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_antecedentes_adicionales', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_antecedentes_adicionales', to='clinica.profesionalsalud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_antecedentes_adicionales', to=settings.AUTH_USER_MODEL)),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clinica.antecedenteadicionalpaciente')),
            ],
            options={
                'verbose_name': 'Cambio de antecedentes adicionales',
                'verbose_name_plural': 'Cambios de antecedentes adicionales',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['empresa', 'paciente', '-fecha'], name='clinica_ant_empresa_f513a5_idx')],
            },
        ),
    ]
