# Generated by Django 5.2.12 on 2026-10-07 00:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0033_antecedenteadicionalpaciente_and_more'),
        ('core', '0054_permisos_gastos_adicionales'),
        ('facturacion', '0079_proveedores_cuenta_habitual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('correlativo', models.PositiveIntegerField(editable=False)),
                ('numero', models.CharField(editable=False, max_length=24)),
                ('observacion', models.TextField(blank=True)),
                ('precio_incluye_impuesto', models.BooleanField(default=False, editable=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha_conversion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_adicionales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('convertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_adicionales_convertidos', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_adicionales_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_adicionales', to='core.empresa')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasto_adicional_origen', to='facturacion.factura')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_adicionales', to='clinica.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_adicionales', to='clinica.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Gasto adicional',
                'verbose_name_plural': 'Gastos adicionales',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaGastoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='clinica.gastoadicional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_gastos_adicionales', to='facturacion.producto')),
            ],
            options={
                'verbose_name': 'Línea de gasto adicional',
                'verbose_name_plural': 'Líneas de gastos adicionales',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gastoadicional',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_ga_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='gastoadicional',
            constraint=models.UniqueConstraint(fields=('empresa', 'correlativo'), name='uniq_ga_empresa_correlativo'),
        ),
    ]
