# Generated by Django 5.2.12 on 2026-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0034_gastos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoadicional',
            name='profesional_nombre',
            field=models.CharField(default='Dr. Luis González', editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='gastoadicional',
            name='tipo_cirugia',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gastoadicional',
            name='tipo_cirugia_nombre',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
