# Generated by Django 5.2.12 on 2026-06-21 01:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_tecnicentro_permisos_y_modulo'),
        ('facturacion', '0052_lineafactura_costo_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BahiaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahias_tecnicentro', to='core.empresa')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTecnicentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(blank=True, max_length=160)),
                ('tiempo_diagnostico_minutos', models.PositiveIntegerField(default=30)),
                ('tiempo_recepcion_minutos', models.PositiveIntegerField(default=15)),
                ('mensaje_recepcion', models.CharField(default='Tu vehiculo fue recibido correctamente.', max_length=300)),
                ('mensaje_listo', models.CharField(default='Tu vehiculo esta listo para ser retirado.', max_length=300)),
                ('notificar_whatsapp', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_tecnicentro', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LineaCotizacionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('repuesto', 'Repuesto'), ('mano_obra', 'Mano de obra'), ('servicio', 'Servicio externo')], max_length=20)),
                ('descripcion', models.CharField(max_length=220)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tecnicentro.cotizaciontaller')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cotizacion_taller', to='facturacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('espera', 'En cola'), ('recepcion', 'Recepcion tecnica'), ('diagnostico', 'Diagnostico'), ('cotizacion', 'Cotizacion'), ('aprobacion', 'Esperando aprobacion'), ('reparacion', 'En reparacion'), ('pruebas', 'Pruebas de calidad'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='espera', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=15)),
                ('motivo_ingreso', models.TextField()),
                ('observaciones_recepcion', models.TextField(blank=True)),
                ('kilometraje_entrada', models.PositiveIntegerField(default=0)),
                ('nivel_combustible', models.CharField(choices=[('reserva', 'Reserva'), ('cuarto', '1/4'), ('medio', '1/2'), ('tres_cuartos', '3/4'), ('lleno', 'Lleno')], default='medio', max_length=20)),
                ('deja_vehiculo', models.BooleanField(default=True)),
                ('autoriza_whatsapp', models.BooleanField(default=True)),
                ('tiempo_espera_estimado_min', models.PositiveIntegerField(default=30)),
                ('tiempo_reparacion_estimado_min', models.PositiveIntegerField(default=60)),
                ('fecha_recepcion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_ingreso_taller', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_listo', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor_recepcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller_recibidas', to=settings.AUTH_USER_MODEL)),
                ('bahia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='tecnicentro.bahiaservicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_taller', to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tecnicentro', to='core.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller', to='facturacion.factura')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recepcion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('espera', 'En cola'), ('recepcion', 'Recepcion tecnica'), ('diagnostico', 'Diagnostico'), ('cotizacion', 'Cotizacion'), ('aprobacion', 'Esperando aprobacion'), ('reparacion', 'En reparacion'), ('pruebas', 'Pruebas de calidad'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tecnicentro.ordenservicio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('recepcion', 'Recepcion'), ('diagnostico', 'Diagnostico'), ('reparacion', 'Reparacion'), ('resultado', 'Resultado final')], max_length=20)),
                ('imagen', models.ImageField(upload_to='tecnicentro/evidencias/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tecnicentro.ordenservicio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas_reportados', models.TextField(blank=True)),
                ('hallazgos', models.TextField()),
                ('causa_probable', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('requiere_prueba_ruta', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado')], default='borrador', max_length=15)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='tecnicentro.ordenservicio')),
            ],
        ),
        migrations.AddField(
            model_name='cotizaciontaller',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='tecnicentro.ordenservicio'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('vin', models.CharField(blank=True, max_length=40)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('turismo', 'Turismo'), ('pickup', 'Pickup'), ('suv', 'SUV'), ('camion', 'Camion'), ('moto', 'Motocicleta'), ('otro', 'Otro')], default='turismo', max_length=20)),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('hibrido', 'Hibrido'), ('electrico', 'Electrico'), ('gas', 'Gas')], default='gasolina', max_length=20)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_tecnicentro', to='core.empresa')),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='tecnicentro.vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='bahiaservicio',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_bahia_codigo_empresa'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'placa'), name='unique_vehiculo_placa_empresa'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_orden_taller_numero_empresa'),
        ),
    ]
