# Generated by Django 5.2.12 on 2026-06-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_empresa_tipo_solucion'),
        ('facturacion', '0052_lineafactura_costo_unitario_and_more'),
        ('tecnicentro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('servicio_solicitado', models.CharField(max_length=220)),
                ('duracion_estimada_min', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada')], db_index=True, default='programada', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_taller', to='facturacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_tecnicentro', to='core.empresa')),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='tecnicentro.ordenservicio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='tecnicentro.vehiculo')),
            ],
            options={
                'ordering': ['fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carroceria', models.CharField(choices=[('buena', 'Sin daños visibles'), ('observaciones', 'Con observaciones'), ('danada', 'Daño evidente')], default='buena', max_length=20)),
                ('llantas', models.CharField(choices=[('buenas', 'Buen estado'), ('desgaste', 'Desgaste visible'), ('danadas', 'Daño o presión baja')], default='buenas', max_length=20)),
                ('parabrisas', models.CharField(choices=[('bueno', 'Sin daños'), ('marcas', 'Marcas menores'), ('quebrado', 'Quebrado o fisurado')], default='bueno', max_length=20)),
                ('luces_tablero_activas', models.BooleanField(default=False)),
                ('porta_documentos', models.BooleanField(default=False)),
                ('llanta_repuesto', models.BooleanField(default=False)),
                ('herramientas', models.BooleanField(default=False)),
                ('radio_pantalla', models.BooleanField(default=False)),
                ('objetos_valor', models.TextField(blank=True)),
                ('danos_existentes', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aceptacion_cliente', models.BooleanField(default=False)),
                ('nombre_aceptante', models.CharField(blank=True, max_length=160)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('inspeccionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion_recepcion', to='tecnicentro.ordenservicio')),
            ],
        ),
    ]
