from django.urls import path
from . import views

urlpatterns = [

    path('', views.facturacion_dashboard, name='facturacion_dashboard'),
    path('configuracion/', views.configuracion_facturacion, name='configuracion_facturacion'),

    path('facturas/', views.facturas_dashboard, name='facturas_dashboard'),
    path('crear/', views.crear_factura, name='crear_factura'),
    path('facturas/prefijo-manual/', views.prefijo_factura_manual, name='prefijo_factura_manual'),
    path('clientes/', views.clientes_facturacion, name='clientes_facturacion'),
    path('clientes/crear/', views.crear_cliente, name='crear_cliente_facturacion'),
    path('clientes/<int:cliente_id>/editar/', views.editar_cliente, name='editar_cliente_facturacion'),
    path('clientes/<int:cliente_id>/eliminar/', views.eliminar_cliente, name='eliminar_cliente_facturacion'),
    path('productos/', views.productos_facturacion, name='productos_facturacion'),
    path('productos/crear/', views.crear_producto, name='crear_producto_facturacion'),
    path('productos/<int:producto_id>/editar/', views.editar_producto, name='editar_producto_facturacion'),
    path('productos/categorias-farmaceuticas/', views.categorias_farmaceuticas, name='categorias_farmaceuticas'),
    path('proveedores/', views.proveedores_facturacion, name='proveedores_facturacion'),
    path('proveedores/crear/', views.crear_proveedor, name='crear_proveedor_facturacion'),
    path('proveedores/<int:proveedor_id>/', views.ver_proveedor, name='ver_proveedor_facturacion'),
    path('proveedores/<int:proveedor_id>/editar/', views.editar_proveedor, name='editar_proveedor_facturacion'),
    path('inventario/', views.inventario_facturacion, name='inventario_facturacion'),
    path('inventario/farmaceutico/', views.inventario_farmaceutico, name='inventario_farmaceutico'),
    path('inventario/farmaceutico/lotes/crear/', views.crear_lote_inventario, name='crear_lote_inventario'),
    path('inventario/farmaceutico/traslados/', views.traslado_inventario_farmaceutico, name='traslado_inventario_farmaceutico'),
    path('inventario/farmaceutico/traslado-rapido/', views.traslado_rapido_farmaceutico, name='traslado_rapido_farmaceutico'),
    path('inventario/entrada/', views.entrada_inventario, name='entrada_inventario'),
    path('inventario/compras/', views.compras_dashboard, name='compras_dashboard'),
    path('inventario/compras/crear/', views.crear_compra, name='crear_compra'),
    path('inventario/compras/<int:compra_id>/editar/', views.editar_compra, name='editar_compra'),
    path('inventario/compras/<int:compra_id>/aplicar/', views.aplicar_compra, name='aplicar_compra'),
    path('inventario/compras/<int:compra_id>/anular/', views.anular_compra, name='anular_compra'),
    path('inventario/compras/<int:compra_id>/pago/', views.registrar_pago_compra, name='registrar_pago_compra'),
    path('inventario/compras/<int:compra_id>/pago/<int:pago_id>/revertir/', views.revertir_pago_compra, name='revertir_pago_compra'),
    path('inventario/compras/<int:compra_id>/', views.ver_compra, name='ver_compra'),
    path('libro-compras/', views.libro_compras_fiscal, name='libro_compras_fiscal'),
    path('libro-compras/importar/', views.importar_libro_compras_fiscal, name='importar_libro_compras_fiscal'),
    path('libro-compras/crear/', views.crear_registro_compra_fiscal, name='crear_registro_compra_fiscal'),
    path('libro-compras/<int:anio>/<int:mes>/', views.libro_compras_fiscal_detalle, name='libro_compras_fiscal_detalle'),
    path('libro-compras/<int:registro_id>/anular/', views.anular_registro_compra_fiscal, name='anular_registro_compra_fiscal'),
    path('inventario/entradas/', views.entradas_inventario_dashboard, name='entradas_inventario_dashboard'),
    path('inventario/entradas/crear/', views.crear_entrada_inventario_documento, name='crear_entrada_inventario_documento'),
    path('inventario/entradas/<int:entrada_id>/', views.ver_entrada_inventario, name='ver_entrada_inventario'),
    path('inventario/ajuste/', views.ajustar_inventario, name='ajustar_inventario'),
    path('inventario/kardex/', views.kardex_inventario, name='kardex_inventario'),
    path('cai/', views.cai_facturacion, name='cai_facturacion'),
    path('cai/crear/', views.crear_cai, name='crear_cai_facturacion'),
    path('cai/<int:cai_id>/editar/', views.editar_cai, name='editar_cai_facturacion'),
    path('cai/<int:cai_id>/eliminar/', views.eliminar_cai, name='eliminar_cai_facturacion'),
    path('impuestos/', views.impuestos_facturacion, name='impuestos_facturacion'),
    path('impuestos/crear/', views.crear_impuesto, name='crear_impuesto_facturacion'),
    path('impuestos/<int:impuesto_id>/editar/', views.editar_impuesto, name='editar_impuesto_facturacion'),
    path('notas-credito/', views.notas_credito_dashboard, name='notas_credito_dashboard'),
    path('recibos/', views.recibos_dashboard, name='recibos_dashboard'),
    path('recibos/<int:recibo_id>/', views.ver_recibo, name='ver_recibo'),
    path('recibos/<int:recibo_id>/pdf/', views.descargar_recibo_pdf, name='descargar_recibo_pdf'),
    path('egresos/', views.egresos_dashboard, name='egresos_dashboard'),
    path('egresos/<int:comprobante_id>/', views.ver_comprobante_egreso, name='ver_comprobante_egreso'),
    path('egresos/<int:comprobante_id>/pdf/', views.descargar_comprobante_egreso_pdf, name='descargar_comprobante_egreso_pdf'),
    path('cierres-caja/', views.cierres_caja, name='cierres_caja'),
    path('cierres-caja/resumen-diario/', views.resumen_diario_caja, name='resumen_diario_caja'),
    path('cierres-caja/<int:cierre_id>/', views.ver_cierre_caja, name='ver_cierre_caja'),
    path('notas-credito/crear/', views.crear_nota_credito, name='crear_nota_credito'),
    path('notas-credito/factura/<int:factura_id>/detalle/', views.detalle_factura_para_nota_credito, name='detalle_factura_para_nota_credito'),
    path('notas-credito/<int:nota_id>/', views.ver_nota_credito, name='ver_nota_credito'),
    path('notas-credito/<int:nota_id>/pdf/', views.descargar_nota_credito_pdf, name='descargar_nota_credito_pdf'),
    path('notas-credito/<int:nota_id>/editar/', views.editar_nota_credito, name='editar_nota_credito'),
    path('notas-credito/<int:nota_id>/anular/', views.anular_nota_credito, name='anular_nota_credito'),

    path('<int:factura_id>/', views.ver_factura, name='ver_factura'),

    path('<int:factura_id>/editar/', views.editar_factura, name='editar_factura'),
    path('<int:factura_id>/validar/', views.validar_factura, name='validar_factura'),

    path('<int:factura_id>/pdf/', views.descargar_factura_pdf, name='descargar_factura_pdf'),
    path('<int:factura_id>/pdf/alternativo/', views.descargar_factura_pdf_alternativo, name='descargar_factura_pdf_alternativo'),
    path('<int:factura_id>/pdf/notas-extensas/', views.descargar_factura_pdf_notas_extensas, name='descargar_factura_pdf_notas_extensas'),
    path('<int:factura_id>/pdf/vista-previa/', views.vista_previa_factura_pdf, name='vista_previa_factura_pdf'),
    path('<int:factura_id>/pdf/alternativo/vista-previa/', views.vista_previa_factura_pdf_alternativo, name='vista_previa_factura_pdf_alternativo'),
    path('<int:factura_id>/pdf/notas-extensas/vista-previa/', views.vista_previa_factura_pdf_notas_extensas, name='vista_previa_factura_pdf_notas_extensas'),

    # 🔥 NUEVO
    path('<int:factura_id>/pago/', views.registrar_pago, name='registrar_pago'),
    path('<int:factura_id>/anular/', views.anular_factura, name='anular_factura'),
    path('<int:factura_id>/eliminar/', views.eliminar_factura_historica, name='eliminar_factura'),
    path('<int:factura_id>/eliminar-borrador/', views.eliminar_factura, name='eliminar_factura_borrador'),
    path('<int:factura_id>/duplicar/', views.duplicar_factura, name='duplicar_factura'),
    path('<int:factura_id>/nota-credito/', views.generar_nota_credito_desde_factura, name='generar_nota_credito_desde_factura'),

    path('reportes/', views.reportes_facturacion, name='reportes_facturacion'),
    path('reportes/dashboard-bi/', views.dashboard_bi_facturacion, name='dashboard_bi_facturacion'),
    path('reportes/power-bi/', views.configuracion_power_bi_reportes, name='configuracion_power_bi_reportes'),
    path('reportes/bancos/', views.reporte_ingresos_bancos, name='reporte_ingresos_bancos'),

    path('cxc/', views.reporte_cxc, name='reporte_cxc'),
    path('cxp/', views.reporte_cxp, name='reporte_cxp'),

    path('reportes/excel/', views.exportar_excel_reportes, name='exportar_excel'),
]
