# Generated by Django 5.2.12 on 2026-08-28 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ampliar_acciones_onix'),
        ('onix_mobile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOnixPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20)),
                ('whatsapp_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('acepta_notificaciones_whatsapp', models.BooleanField(default=False)),
                ('zona_horaria', models.CharField(default='America/Tegucigalpa', max_length=64)),
                ('canal_recordatorio', models.CharField(choices=[('app', 'Aplicacion'), ('correo', 'Correo'), ('whatsapp', 'WhatsApp')], default='app', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_onix_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil personal de Onix',
                'verbose_name_plural': 'Perfiles personales de Onix',
            },
        ),
        migrations.CreateModel(
            name='SolicitudOAuthOnix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('apple_calendar', 'Calendario de iPhone'), ('gmail', 'Gmail'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('estado_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('consumida_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_oauth_onix', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_oauth_onix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud OAuth de Onix',
                'verbose_name_plural': 'Solicitudes OAuth de Onix',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConexionOnixExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('apple_calendar', 'Calendario de iPhone'), ('gmail', 'Gmail'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conectada', 'Conectada'), ('error', 'Error'), ('revocada', 'Revocada')], db_index=True, default='pendiente', max_length=12)),
                ('cuenta_externa', models.CharField(blank=True, max_length=254)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=180)),
                ('permisos', models.JSONField(blank=True, default=list)),
                ('token_acceso_cifrado', models.TextField(blank=True, editable=False)),
                ('token_refresco_cifrado', models.TextField(blank=True, editable=False)),
                ('token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('sincronizacion_activa', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, max_length=500)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_onix', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_onix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexion externa de Onix',
                'verbose_name_plural': 'Conexiones externas de Onix',
                'indexes': [models.Index(fields=['empresa', 'proveedor', 'estado'], name='onix_conexion_estado_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'empresa', 'proveedor'), name='onix_conexion_unica_usuario_empresa')],
            },
        ),
    ]
