from django.urls import path

from . import views


urlpatterns = [
    path("", views.clinica_dashboard, name="clinica_dashboard"),
    path("pacientes/", views.pacientes, name="clinica_pacientes"),
    path("pacientes/sugerencias/", views.pacientes_sugerencias, name="clinica_pacientes_sugerencias"),
    path("pacientes/crear/", views.crear_paciente, name="clinica_crear_paciente"),
    path("pacientes/enlace-registro/generar/", views.generar_enlace_registro_paciente, name="clinica_generar_enlace_registro_paciente"),
    path("pacientes/<int:paciente_id>/", views.paciente_detalle, name="clinica_paciente_detalle"),
    path("pacientes/<int:paciente_id>/editar/", views.editar_paciente, name="clinica_editar_paciente"),
    path("pacientes/<int:paciente_id>/eliminar/", views.eliminar_paciente, name="clinica_eliminar_paciente"),
    path("pacientes/<int:paciente_id>/recordatorios-tratamiento/crear/", views.crear_recordatorios_tratamiento, name="clinica_crear_recordatorios_tratamiento"),
    path("pacientes/<int:paciente_id>/expediente/agregar/", views.crear_evento_expediente, name="clinica_crear_evento_paciente"),
    path("pacientes/<int:paciente_id>/evolucion/", views.evolucion_paciente, name="clinica_evolucion_paciente"),
    path("pacientes/<int:paciente_id>/evolucion/registrar/", views.registrar_foto_evolucion, name="clinica_registrar_foto_evolucion"),
    path("pacientes/<int:paciente_id>/examenes/", views.examenes_paciente, name="clinica_examenes_paciente"),
    path("pacientes/<int:paciente_id>/examenes/subir/", views.subir_examen_paciente, name="clinica_subir_examen_paciente"),
    path("pacientes/<int:paciente_id>/recetas/", views.recetas_paciente, name="clinica_recetas_paciente"),
    path("pacientes/<int:paciente_id>/recetas/crear/", views.crear_receta_paciente, name="clinica_crear_receta_paciente"),
    path("pacientes/<int:paciente_id>/recetas/<int:receta_id>/imprimir/", views.imprimir_receta_paciente, name="clinica_receta_imprimir"),
    path("pacientes/<int:paciente_id>/consentimientos/", views.consentimientos_paciente, name="clinica_consentimientos_paciente"),
    path("pacientes/<int:paciente_id>/consentimientos/subir/", views.subir_consentimiento_paciente, name="clinica_subir_consentimiento_paciente"),
    path("pacientes/<int:paciente_id>/historias/", views.historias_especialidad, name="clinica_historias_especialidad"),
    path("pacientes/<int:paciente_id>/historias/consolidado/", views.historial_clinico_consolidado, name="clinica_historial_clinico_consolidado"),
    path("pacientes/<int:paciente_id>/historias/nueva/<slug:tipo>/", views.crear_historia_especialidad, name="clinica_crear_historia_especialidad"),
    path("pacientes/<int:paciente_id>/historias/<int:historia_id>/editar/", views.editar_historia_especialidad, name="clinica_editar_historia_especialidad"),
    path("pacientes/<int:paciente_id>/preconsulta/generar/", views.generar_enlace_preconsulta, name="clinica_generar_enlace_preconsulta"),
    path("pacientes/<int:paciente_id>/preconsulta/generar/<slug:tipo>/", views.generar_enlace_preconsulta, name="clinica_generar_enlace_preconsulta_tipo"),
    path("pacientes/<int:paciente_id>/preconsulta/<int:preconsulta_id>/enviar-whatsapp/", views.enviar_preconsulta_whatsapp, name="clinica_enviar_preconsulta_whatsapp"),
    path("pacientes/<int:paciente_id>/preconsulta/<int:preconsulta_id>/", views.preconsulta_detalle, name="clinica_preconsulta_detalle"),
    path("citas/", views.citas, name="clinica_citas"),
    path("citas/crear/", views.crear_cita, name="clinica_crear_cita"),
    path("citas/pacientes/crear-rapido/", views.crear_paciente_rapido_cita, name="clinica_crear_paciente_rapido"),
    path("expediente/agregar/", views.crear_evento_expediente, name="clinica_crear_evento"),
    path("tratamientos/", views.tratamientos, name="clinica_tratamientos"),
    path("tratamientos/crear/", views.crear_tratamiento, name="clinica_crear_tratamiento"),
    path("profesionales/", views.profesionales, name="clinica_profesionales"),
    path("profesionales/<int:profesional_id>/editar/", views.editar_profesional, name="clinica_profesional_editar"),
    path("servicios/", views.servicios, name="clinica_servicios"),
]
